### ISSUE TITLE
Question about unexpected gaps

### ISSUE THREAD

**Issue by zhousun21** [malonge/RagTag#100]
Hi Malonge,
Thank you for this very useful program.

I have a question about unexpected gaps.  I ran a small test of a reference of 1000 nt, and a target consisting of three contigs corresponding to overlapping fragments of the reference.  I ran RagTag and assumed the results would be identical to the reference.  Instead I got a scaffold with two gaps. 

I have attached the reference, target, and output files. 
The command I used was:
ragtag.py scaffold -u -w reference.fasta target.fasta &

Any idea what happened?  (Note: I had to zip the files to attach them here.  The command was run on unzipped files.)
[reference.fasta.gz](https://github.com/malonge/RagTag/files/7919212/reference.fasta.gz)
[target.fasta.gz](https://github.com/malonge/RagTag/files/7919213/target.fasta.gz)
[ragtag.scaffold.fasta.gz](https://github.com/malonge/RagTag/files/7919214/ragtag.scaffold.fasta.gz)

**Comment by malonge** [comment]
Hi there,

Yes this is the expected result given the definition of scaffolding. Please see the [paper](https://doi.org/10.1101/2021.11.18.469135) or the [docs](https://github.com/malonge/RagTag/wiki) for more details.

It sounds like `patch` may be what you are looking for.

**Comment by zhousun21** [comment]
Thanks for clarifying, and for the super-fast response.
