### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ragtag_agp2fa.py': 'ragtag_agp2fa.py'

### ISSUE THREAD

**Issue by aaronphillips7493** [malonge/RagTag#102]
Hey,

Thanks for the awesome tool!

I have installed RagTag by the git clone method and have done the subsequent install step. Everything runs fine until RagTag tries to build the fasta scaffold file. I get the error in the title. I have attached the log file to this post. Do you know of a fix for this? I know I can run the ragtag_agp2fa.py script on its own, but it would be better if the whole thing ran as one job, as I don't know if I am also now missing more downstream steps. 

[slurm-12533098.out.txt](https://github.com/malonge/RagTag/files/7968553/slurm-12533098.out.txt)

Thanks,
Aaron :)

**Comment by malonge** [comment]
Hi there,

It looks like something went wrong with the install. Could you share the exact commands you used to download and install?

Thanks

**Comment by aaronphillips7493** [comment]
Hey,

I followed these commands from the Installation section of the Wiki:
```
git clone https://github.com/malonge/RagTag
cd RagTag
python3 setup.py install
```
Aaron

**Comment by malonge** [comment]
Yeah that looks good to me. Maybe you can share the output from that command so we can check for any irregularities?

**Comment by aaronphillips7493** [comment]
I just tried the install again to get the output of:
`python3 setup.py install`
I didn't notice anything strange, so re-ran RagTag, and it worked this time...I have no idea why haha maybe I was using the wrong version of python the first time I installed RagTag.
