### ISSUE TITLE
Error in merge with Hi-C related to bam index

### ISSUE THREAD

**Issue by SamCT** [malonge/RagTag#103]
Hello,

I just wanted to ask this question because it seems unusual for RagTag to be asking that the Hi-C bam file is sorted by -n (read name). I sorted it and am now being asked for an index file, but you cannot index a read-name sorted bam file. Not with samtools index atleast. Hoping someone can clarify: should I be using an index file generated from a default .bam file (coordinated-sorted), with the same name as the sort -n .bam file such that it can be accessed by ragtag?

Thanks,
Sam

**Comment by malonge** [comment]
Hi Sam,

Thanks for reaching out. Sorting by read name is commonly used to process Hi-C reads because reads must be analyzed as a pair, and sorting by read names groups read pairs together. What exactly is asking you for an index file? Is this a RagTag error?

Thanks,
Mike

**Comment by SamCT** [comment]
Yes it's a rag tag error. Here is what I am getting.

INFO: Computing raw Hi-C links from: /path/file_sortN.bam
[E::idx_find_and_load] Could not retrieve index file for '/path/file_sortN.bam'
Traceback (most recent call last):
  File "/path/ragtag_create_links.py", line 242, in <module>
    main()
  File "/path/ragtag_create_links.py", line 213, in main
    raw_links = count_links(bam_file, l_cutoffs, r_cutoffs)
  File "/path/ragtag_create_links.py", line 82, in count_links
    if prev_pos <= l_cutoffs[prev_r_name]:
KeyError: 'scaffold_6_length_47512341'


Thanks for the reply,
Sam

**Comment by malonge** [comment]
ah ok so the line `[E::idx_find_and_load] Could not retrieve index file for '/path/file_sortN.bam'` is more like a warning. It is definitely confusing but the program should actually be able to run without an index. Actually its the second error that is causing a problem: 

`KeyError: 'scaffold_6_length_47512341'`

My guess is that the assembly file that you input into `ragtag.py merge` is not the same assembly to which you aligned the Hi-C reads. Is that right?

Thanks

**Comment by SamCT** [comment]
Ah okay, thank you for clearing it up and the quick response.

Yes that's correct -- I thought I might be able to align the hi-c reads to previous reference, in order to update the newer assembly. I've got other bam alignments to the new assembly so I'll try that and report back soon so we can confirm and close the issue ticket.

Thanks again,
Sam

**Comment by malonge** [comment]
Thanks. I should output a more helpful error message.

**Comment by SamCT** [comment]
It seems to be running! Thanks again Mike
