### ISSUE TITLE
Scaffolding non-model plant genomes

### ISSUE THREAD

**Issue by rotoke** [malonge/RagTag#106]
Dear Mike,

I'm working on a non-model plant species with no published genomic data available. This plant species includes several subspecies, which are very closely related but differ significantly in genome size (2n = 1.5-2.1 Gbp, all diploid). K-mer analyses indicate that the transposon load is relatively constant across subspecies, suggesting that the genome size differences are partially due to duplicated or introgressed segments. I have a Hi-C scaffolded PacBio CLR assembly of the subspecies with the largest genome, as well as unscaffolded PacBio HiFi assemblies of two additional subspecies with smaller genomes.

1.  What would happen to duplicated regions if I attempt to scaffold the assemblies of the two subspecies with smaller genomes using the assembly of the subspecies with larger genome as reference? I assume ragtag does not duplicate contigs, but could this scramble up contig order within the scaffolds fo the smaller assemblies?

2.  The Hi-C scaffolded reference contains 6 chromosome-size scaffolds plus some 1500 small contigs which could not be joined. Would I need to provide the entire assembly as reference, or can I disregard the unjoined contigs for scaffolding?

Thanks,
Roman

**Comment by rotoke** [comment]
Update: I gave it a try for one subspecies both with minimap2 and nucmer to the 6 large scaffolds only.
Here is a circos plot of the unscaffolded contigs (not all contigs shown):

![naries_springbok](https://user-images.githubusercontent.com/67823452/155796514-3b84327d-cdb8-4504-9993-b90b034e866a.png)

Here are both circos and dot plot of the ragtag scaffolds using minimap2 with -asm20 (nucmer gave quite similar results):

![naries_asm20_springbok](https://user-images.githubusercontent.com/67823452/155800190-398684e9-ca61-45f6-8f8a-dbb4553d3440.png)

![map_2_naries_six_to_1_springbok_six](https://user-images.githubusercontent.com/67823452/155800241-cf3b2604-0ad0-473b-bd2b-4794efd56928.png)

I don't see large duplications, but quite a few gaps and inversions. I assume the gaps are either real or due to missing repetitive sequences, but I am wondering whether all the inversions are real (especially the large one on scaffold 2). Is it possible to test this somehow without generating additional Hi-C data?

Thank you very much in advance,
Roman

**Comment by malonge** [comment]
Hi there,

Thanks for reachng out. The first question is a little technically esoteric so perhaps the best place to start is to read the methods of the papers and let me know if you still have questions: https://github.com/malonge/RagTag#citation 

For the second question, I generally recommend against omitting certain sequences from the reference just for the purpose of scaffolding.

As for validating the results, I definitely recommend validating the scaffolds with independent data if possible. Sometimes structural rearrangements represent genuine variation and sometimes they are misassemblies or scaffolding errors.

Thanks,
Mike
