### ISSUE TITLE
Asking RagTag correction and scaffold running time

### ISSUE THREAD

**Issue by NuruddinKhoiry** [malonge/RagTag#107]
Dear Mike,

I am running RagTag correction and scaffold for an insect genome (372 Mb).

For RagTag correction, I am stuck in this step for many hours:

Wed Feb 23 14:02:49 2022 --- INFO: Compressing, sorting, and indexing read alignments
Wed Feb 23 14:46:51 2022 --- INFO: Indexing read alignments
Wed Feb 23 14:50:45 2022 --- INFO: Validating putative query breakpoints
Wed Feb 23 14:50:45 2022 --- INFO: Calculating global read coverage
Wed Feb 23 14:56:03 2022 --- INFO: The global median read coverage is 1X
Wed Feb 23 14:56:03 2022 --- INFO: The max and min coverage thresholds are 12X and 5X, respectively
........ ## It is still running and I haven't got any result until now.....

For RagTag scaffold, I am stuck in this step (writing AGP) for many days:
INFO: Writing scaffolds
INFO: Writing: home_bif/khoiri/genome/ragtag_output/ragtag.scaffolds.agp
........ ## It is still running and I haven't got any result until now.....

My question is that is this condition normal or is there something wrong with my RagTag installation? As I noticed from this issue [#28](https://github.com/malonge/RagTag/issues/28), it took only a few time to write a .agp file in the RagTag scaffold step.

my VERSION: RagTag v2.1.0

Thanks,
Khoiri

**Comment by malonge** [comment]
Hi there,

Yes that is definitely unusual unless your assembly has millions of contigs or something. Even then, days seems quite long. How many contigs are in your assembly?

Thanks,
Mike

**Comment by NuruddinKhoiry** [comment]
Dear Mike,

Thank you for the reply. 
My contigs are 18,654,433. These contigs were originated from Illumina short reads. I used SOAPdenovo2 for the assembly.

Thanks,
Khoiri

**Comment by malonge** [comment]
Yes that is very large number of contigs. You may consider removing contigs shorter than a certain size (I recommend 500bp or 1kb)
