### ISSUE TITLE
Query sequence in patch function

### ISSUE THREAD

**Issue by sunandan-dasgupta** [malonge/RagTag#108]
Dear Dr. Alonge,
    I am using RagTag for generating scaffolds for using in a taxonomic project I am working on. In this project, we are looking into the possible cryptic species diversity in multiple subpopulations of a fish that is currently classified as one species but may actually be a complex of multiple closely related species.
   The sequence data I am using are low coverage (10 X), paired end short Illumina HiSeq reads. I have made the contigs using AbySS 2.0 and I have used one high quality published reference genome to scaffold the contigs in RagTag. I scaffolded the contigs first as I read from one of your past answers to another user's query that scaffold function is more sensitive and makes more joins.
  Now, I would like to close the gaps. As you know by now, I do have a high quality reference genome (which I used for scaffolding) but as you can see, the subpopulation from which the reference genome was generated may not belong to the same species with all the other samples I have (though it will be very closely related for sure). Therefore, is it possible that I use Abyss generated contigs fasta file for a particular sample as the query and RagTag generated scaffold of that same sample as target in patch function? Is this a valid approach?
  Or do you recommend that I use the reference sequence as query for gap closing (whereas the RagTag generated scaffold will be the target)? The only reason I am hesitating to do this a bit is, as I have stated, there is a possibility that the high quality reference may not be conspecific (though closely related) with some of my samples and to my beginner level understanding, if I use that as a query, then gaps in the target scaffold will be filled with sequence coming straight from the reference. Instead, I want gap filling in, say, scaffold A to be informed by contigs of sample A.  
  Or do you suggest some other approaches in RagTag?
I apologise if my query is naive but please excuse me as I am a beginner in the world of large scale genome assembly. 
Sincere thanks in advance for your kind suggestions, also thanks for developing this highly useful tool.

**Comment by malonge** [comment]
Hi there,

The assemblies should represent the same genome unless you have a really good reason to create a mosaic assembly. For a beginner, I definitely recommend only using assemblies that represent the same genome.

Thanks,
Mike
