### ISSUE TITLE
Scaffolding Error

### ISSUE THREAD

**Issue by bgmfddg** [malonge/RagTag#109]
Hi,
ragtag scaffold stops with the following error message:

(fp) wuhan@root640:/data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail$ ragtag.py scaffold NC_015506.1.fasta metacompass_assembly/metacompass_output/metacompass.final.ctg.fa -t 32 -u -w --debug
Tue Mar 15 11:04:26 2022 --- VERSION: RagTag v2.1.0
Tue Mar 15 11:04:26 2022 --- CMD: ragtag.py scaffold NC_015506.1.fasta metacompass_assembly/metacompass_output/metacompass.final.ctg.fa -t 32 -u -w --debug
Tue Mar 15 11:04:26 2022 --- INFO: Mapping the query genome to the reference genome
Tue Mar 15 11:04:26 2022 --- INFO: Overwriting pre-existing file: /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/ragtag_output/ragtag.scaffold.asm.paf
Tue Mar 15 11:04:26 2022 --- INFO: Running: minimap2 -x asm5 -t 32 /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/NC_015506.1.fasta /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/metacompass_assembly/metacompass_output/metacompass.final.ctg.fa > /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/ragtag_output/ragtag.scaffold.asm.paf 2> /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/ragtag_output/ragtag.scaffold.asm.paf.log
Tue Mar 15 11:04:26 2022 --- INFO: Finished running : minimap2 -x asm5 -t 32 /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/NC_015506.1.fasta /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/metacompass_assembly/metacompass_output/metacompass.final.ctg.fa > /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/ragtag_output/ragtag.scaffold.asm.paf 2> /data/12T-2/wh/PRJEB21674/data/90/ragtag_fail/ERR2040790fail/ragtag_output/ragtag.scaffold.asm.paf.log
Tue Mar 15 11:04:26 2022 --- INFO: Reading whole genome alignments
Tue Mar 15 11:04:26 2022 --- INFO: Filtering and merging alignments
Traceback (most recent call last):
  File "/home/root640/software/miniconda3/envs/fp/bin/ragtag_scaffold.py", line 577, in <module>
    main()
  File "/home/root640/software/miniconda3/envs/fp/bin/ragtag_scaffold.py", line 488, in main
    raise RuntimeError("There are no useful alignments. Check output alignment files.")
RuntimeError: There are no useful alignments. Check output alignment files.

And the ragtag.scaffold.debug.* files are empty.
Sincere thanks in advance for your kind suggestions, also thanks for developing this highly useful tool.
#84

**Comment by malonge** [comment]
Hi there,

This means that, at least after filtering, there were no "useful" alignments between the two assemblies. I recommend trying to align these assemblies with external tools like Minimap2 and Nucmer and manually check the results. This is likely not a bug with RagTag, but rather a problem with the assemblies.

Thanks,
Mike
