### ISSUE TITLE
Patch seqs input (Hifi contigs to fill ONT ultra-long assembly gaps)?

### ISSUE THREAD

**Issue by hrluo93** [malonge/RagTag#110]
Hi，

If I want to use Hifi contigs to fill ONT ultra-long assembly gaps
following steps are correct?
correct ont assembly with ref genome 
scaffold ONT assembly to ref genome
use Hi-C to resolve conflicts in above result fasta by merge function 
so, in patch : Hi-C resolved fasta as target fasta file and Hifi contigs set as query fasta? 
does my stpes correct? 
Thank you very much!

**Comment by malonge** [comment]
Hi there,

That sounds close to what I would recommend. I would just add the following: 

1) Honestly with newer ONT/PacBio data, `correct` is usually not necessary. I may even produce more errors than it fixes. So I would only use `correct` if you have a good reason for doing so.

2) I would patch first, then scaffold.

3) For scaffolding, you can do reference-guided scaffolding with RagTag, Hi-C based scaffolding with another tool like SALSA2, or you can do both and merge them with `merge` (like we do in the preprint). It's up to you to decide which route will produce the most accurate results. Every situation is different, so I recommend trying multiple options and assessing the accuracy of each. You may even need to do some manual scaffolding (also like what we do in the preprint).

Thanks,
Mike
