### ISSUE TITLE
ValueError: Input AGPs do not have the same set of components.

### ISSUE THREAD

**Issue by linshengnan09** [malonge/RagTag#111]
Hi @malonge ,
I have two references, so I used one to correct and then both to scaffold. When merge the two AGPs generated by scaffold step, here met an error:
    raise ValueError("Input AGPs do not have the same set of components.")
ValueError: Input AGPs do not have the same set of components.
could you tell me how to solve this problem?
Thank you!

**Comment by malonge** [comment]
Hi there,

Please read the [wiki](https://github.com/malonge/RagTag/wiki/merge#positional-arguments) for more info. Basically, your input AGP files do not scaffold the same assembly:


>`<asm.fasta>` is the input genome assembly that we wish to scaffold. This is followed by at least two AGP files (`<scf1.agp> <scf2.agp> [...]`), each representing an individual scaffolding of `<asm.fasta>`.

It may also help to read about the [AGP file format](https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/) to understand what is meant by "components".

**Comment by linshengnan09** [comment]
您好，您的邮件我已收到。祝生活愉快，工作顺利！

**Comment by mmpust** [comment]
Hey, I am running into a similar issue. So, would you recommend not to correct the assembly before scaffolding the same assembly with difference reference sequences?
Thanks!
