### ISSUE TITLE
RagTag not recognizing minimap2 executable?

### ISSUE THREAD

**Issue by Mpersicae** [malonge/RagTag#12]
Hello,

I am trying to run RagTag on a desktop with Ububtu 18.04. I would like to use Minimap2 as an aligner, and have installed Minimap2 in my home directory. When I run the following RagTag command:

```
ragtag.py scaffold ~/Desktop/M_Per_G006/MPER_G006.fa ~/Desktop/canu-wtdbg2/canu-wtdbg2-consensus-2-clean.fasta \
-o ~/ragtag/M-per -u --aligner '~/minimap2/minimap2' --mm2-params '-x map-pb'
```

I get the following error:

`ValueError: The provided aligner executable is not valid: ~/minimap2/minimap2`

I am fairly certain minimap2 is correctly installed, because I can call the executable using `~/minimap2/minimap2 -h`

I'll include the entire output here as well, for reference:
```
Thu Jul 23 14:36:57 2020 --- RagTag v1.0.0
Thu Jul 23 14:36:57 2020 --- CMD: /usr/local/bin/ragtag_scaffold.py /home/yonathan/Desktop/M_Per_G006/MPER_G006.fa /home/yonathan/Desktop/canu-wtdbg2/canu-wtdbg2-consensus-2-clean.fasta -o /home/yonathan/ragtag/M-per -u --aligner $HOME/minimap2/minimap2 --mm2-params -x map-pb
Thu Jul 23 14:36:57 2020 --- Mapping the query genome to the reference genome
Traceback (most recent call last):
  File "/usr/local/bin/ragtag_scaffold.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==1.0.0', 'ragtag_scaffold.py')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/RagTag-1.0.0-py3.6.egg/EGG-INFO/scripts/ragtag_scaffold.py", line 528, in <module>
  File "/usr/local/lib/python3.6/dist-packages/RagTag-1.0.0-py3.6.egg/EGG-INFO/scripts/ragtag_scaffold.py", line 377, in main
  File "/usr/local/lib/python3.6/dist-packages/RagTag-1.0.0-py3.6.egg/ragtag_utilities/Aligner.py", line 126, in run_aligner
  File "/usr/local/lib/python3.6/dist-packages/RagTag-1.0.0-py3.6.egg/ragtag_utilities/Aligner.py", line 116, in exec_is_valid
ValueError: The provided aligner executable is not valid: $HOME/minimap2/minimap2
```

Thanks! 
Y.

**Comment by malonge** [comment]
Hi there,

Thanks for bringing this to my attention. Did you enter `--aligner $HOME/minimap2/minimap2` or `--aligner '~/minimap2/minimap2'`. You will notice that the output states that the former was entered, and that may be causing the problem. The CMD log is generated with the following:

https://github.com/malonge/RagTag/blob/fb2f7ca523075d323d3f93b709e6304360c539d6/ragtag_scaffold.py#L284

So for some reason, `--aligner $HOME/minimap2/minimap2` is what is in the `sys.argv`, i.e. how python parsed your command.

I am not sure but you may also consider using double instead of single quotes.

**Comment by Mpersicae** [comment]
Hi Michael,

Thanks for your response. Removing the single quotes from the minimap2 path solved the issue. I'm not sure why python parsed the command that way but it seems to have figured itself out. 

Thanks again!
Y.
