### ISSUE TITLE
AGP2FA: KeyError: "sequence 'tig00001068' not present"

### ISSUE THREAD

**Issue by leone93** [malonge/RagTag#124]
Hi, I have found this error using agp2fasta to scaffold my assembly starting from an agp file.
I have previously check the agp with the agpcheck utility.
I check also if the contig is present in my fasta and yes it is.
I simply run the application with `ragtag.py agp2fa ragtag.scaffold.rename.ChrUn.agp aus_phill.fasta`

I don't understand where the problem can be.
Any idea?

**Comment by leone93** [comment]
solved. the fai index was wrong.

**Comment by Immortal2333** [comment]
> solved. the fai index was wrong.

**Thank you so much for your reminder!!!**
