### ISSUE TITLE
glibc UnsatisfiableError:

### ISSUE THREAD

**Issue by rupesh-sinha** [malonge/RagTag#126]
# Hi
# I am trying to install RagTag in Conda environment but getting the following error:

(allenv) streptomyces@SBIO-KT-LIN-2:~/Rupesh/Kapil/kraken_processed_snippy$ conda install -c bioconda ragtag 
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed    

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

# Kindly help!
# Thanks

**Comment by fer-res89** [comment]
I'm having the same issue, I hope someone can solve this soon

**Comment by malonge** [comment]
Hi there,

I recommend installing with a conda environment and that should do the trick. This is general conda advice and not a specific ragtag issue.
