### ISSUE TITLE
Which utility to use to stitch scaffolds into a single assembly

### ISSUE THREAD

**Issue by Rohit-Satyam** [malonge/RagTag#128]
Hi!!

I have scaffolds from SARS-Cov-2 PAIRED END sequencing data generated using `coronaSPADES`. I now wish to stitch them together into single sequences using a SARS-COV-2 reference fasta file with `NNN` repeats in the region where there is no sequence. I am confused which `RagTag` utility will be most suitable for this? `scaffold` or `patch` because when I use `scaffold` it just orders my scaffolds rather then joining them to form single assembly.

**Comment by malonge** [comment]
Hi there,

Based on your description, you would want `scaffold`. The output scaffolded assembly is `ragtag.scacffold.fasta`

Thanks,
Mike
