### ISSUE TITLE
Is it possible to pass multiple references for scaffolding? I have two reference strain for my contigs

### ISSUE THREAD

**Issue by Rajeefa** [malonge/RagTag#13]

**Comment by malonge** [comment]
Hi there,

[RagTag scaffolding](https://github.com/malonge/RagTag/wiki/Scaffolding) can only be used with a single reference assembly and a single query assembly.

My advice is to run ragtag twice, once for each of the two references. Then, save the scaffolding AGP files. I am actively working on a RagTag feature that would reconcile the two AGP files, effectively using both references for scaffolding. I will leave this issue open until that feature is ready.

**Comment by gracem97** [comment]
Hi, 
This is somewhat unrelated to the thread, but do you think ti is possible to use a Flye assembly as the reference to map contigs onto? 
I tried this instead of a published reference and ragtag gave an output with more than one read. 

ty

**Comment by malonge** [comment]
Hi @gracem97 ,

You can use any assembly you'd like as the reference. It's up to you to decide which is best to inform scaffolding of the query assembly. If you are getting odd results, feel free to open another issue and I would be happy to help you debug.

Thanks

p.s. As per the original issue, soon you will be able to use both assemblies as the reference! So in anticipation of that feature (which I am currently developing), you can use both assemblies as the reference (in separate runs) and save the AGP output for each. When the feature is ready, the AGP files will be what you need as input.

**Comment by malonge** [comment]
@Rajeefa This functionality is now available with `ragtag.py merge`, which is available in RagTag v1.1.0. Updated documentation in the wiki is forthcoming.
