### ISSUE TITLE
Skipping alignment through available paf file

### ISSUE THREAD

**Issue by supermaxiste** [malonge/RagTag#15]
Hello,

I'm using `RagTag` to map an assembly to a chromosome-level assembly and everything worked perfectly with both `minimap2` and `nucmer`. Great tool!

Since it's the first time I'm doing this kind of mapping and since the results are quite different between `minimap2` and `nucmer`, I'm also using `lastal` for the same task to check the consistency between all mappings. I was able to generate a `paf` file for `lastal` and I was wondering if there was a way (and if it was possible) to run `RagTag` without mapping, given that a `paf` file is provided.

Thank you in advance for your answer!

**Comment by malonge** [comment]
Hi there,

I am glad things have worked out so far. If you are not running with `-w`, RagTag won't overwrite preexing output files. So you can rename your alignments as `query_against_ref.paf` and place them in `ragtag_output` (or whatever you specified with `-o`). ragtag will then use those alignments instead. 

The same thing goes for the correction module, though the file name should be `c_query_against_ref.paf`.

Thanks

**Comment by supermaxiste** [comment]
Hi Micheal,

I tried what you suggested and it worked exactly as you said. May I suggest to add this tip somewhere in the Wiki? Might be useful to other people too and it's somehow an extra feature.

Thank you again for the help!

Stefan

**Comment by malonge** [comment]
Hi there,

Thanks for the suggestion. I definitely plan to make this option more obvious to users somehow, but I am still thinking about the details. 

Thanks
