### ISSUE TITLE
How to pass minimap2 parameters?

### ISSUE THREAD

**Issue by evo-eco-gen** [malonge/RagTag#151]
Hi,

I ran the following command hoping to get a .paf with CIGAR strings (to then convert into .delta): RagTag took 20x longer, but did not return the CIGAR... Could you provide an example of how to pass minimap2 parameters, please?

ragtag.py scaffold my_ref my_query -f 1000 -q 10 -d 100000 -i 0.2 -a 0.0 -s 0.0 -g 100 -m 1000000 --remove-small -u \
 --mm2-params '-c -t12'

**Comment by malonge** [comment]
I can't explain this, especially if it did take longer to run. Perhaps use double quotes?

Anyways at least you can just generate the paf file how ever you want independently. Instructions [here](https://github.com/malonge/RagTag/issues/86).
