### ISSUE TITLE
Cases where missassembly correction and patching aren't needed

### ISSUE THREAD

**Issue by sjfleck** [malonge/RagTag#153]
Hello,
thank you for the useful program. I'm working with one chromosomal-level assembly that I created and would like to scaffold twenty-two other members of the genus that we have haploid MaSuRCA assemblies for. Luckily, these other species have the same chromosome number and ploidy level as our chromosome-level assembly. 

I've already run RagTag-2.1.0 using "ragtag.py scaffold" alone. The resulting genomes and GeMoMa annotations were very good. I'm now questioning if I should have used correct and patch as well. A similar method was done using RagTag-v1.0.1 in another publication ([huff et al. 2021](https://onlinelibrary.wiley.com/doi/full/10.1111/1755-0998.13545)), but they didn't say which commands they used, but they also have a lot of Ns in those assemblies. I'm seeing now that patch wasn't incorperated until v2.0.0, so it looks like they didn't even have the option to patch. This was all I could find on their method:

"For all 28 assemblies, we used RagTag v1.0.1 to align the scaffolds of each assembly to the chromosomes of F. pennsylvanica and join them to produce chromosome-scale assemblies"

I don't want to potentially miss the actual variation between these species by using correcting the misassemblies. Additionally, The MaSuRCA RagTag assemblies have a lot (between 14k and 28k) of N's per 100 kbp (except one highly contiguous long-read assembly that only had 224.36 Ns per 100 kbp). I'm worried that patching these gaps with the chromosome-level assembly might not be the right option, but I'm unsure. Any insight into this topic would be greatly appreciated.

**Comment by malonge** [comment]
It's up to your discretion and all assemblies should be validated/curated before publication to ensure accuracy.

That said, generally speaking, correction is a bad idea for assemblies of different species. Its great for two assemblies of the same haplotype and sometimes it can be used for multiple haplotypes in the same species. But I would advise against using correction between species. The same goes for "patch".
