### ISSUE TITLE
Scaffold doesn't run

### ISSUE THREAD

**Issue by aebaci** [malonge/RagTag#154]
Hi:

I have tried to run the scaffold option of ragtag, but I get an error message (below). It says it doesn't have the ragtag_scaffold.py, but I go to the folder and it was installed there (same folder as ragtag.py), so I'm not sure what to do. I tried the other commands and they give the same error, changing the executable file that is not found (and they are all there).
I really hope to use this tool for my assemblies, so if you could help me out it would be great. Thanks! 
Software version is v2.1.0
/opt/mambaforge/bin/ragtag.py scaffold RprolixusVB.fasta racon1Rprol2.fasta 
Traceback (most recent call last):
  File "/opt/mambaforge/bin/ragtag.py", line 133, in <module>
    main()
  File "/opt/mambaforge/bin/ragtag.py", line 89, in main
    subprocess.call(subcmd)
  File "/opt/mambaforge/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/opt/mambaforge/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/mambaforge/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ragtag_scaffold.py'

**Comment by malonge** [comment]
There is just some sort of installation issue. I recommend just using conda or pypi if you are having difficulty installing from source. Also consider virtual environments to make things easier to interpret.
