### ISSUE TITLE
A question about "correct" step in RagTag, I need help!

### ISSUE THREAD

**Issue by link-xhx** [malonge/RagTag#158]
I'm just a student new to genome-related research and analysis, I think RagTag software is great！Thank a lot！

Recently, I use RagTag software to help me optimise the contigs I assembled using SOAPdenove2 software. 
I run programs on linux servers (1.5T running memory), in "correct" step, I input the contigs I assembled using SOAPdenove2 software and reference genome, contigs size 36.41 GB, reference genome size 2.83 GB, and the input code is “nohup ragtag.py correct GCA_025200525.1_XYYC_v1.0_genomic.fna graph_prefix.contig -t 8 &”.
But ten days have passed and the "correct" step is not over yet, I don‘t know why！Is this normal? Did I do something wrong? 

**Now, this is what the server displays when the TOP command is used:**
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                      
366086 xiehaox+  20   0  155.5g 135.9g   2900 R  99.7  9.0  18992:49 ragtag_correct.                                                                                                                  
 28576 xiehaox+  20   0  163352   3532   1600 R   1.0  0.0   0:02.03 top   

**Now, nohup.out file show:**
Mon Mar 20 02:23:52 2023 --- VERSION: RagTag v2.1.0
Mon Mar 20 02:23:52 2023 --- CMD: ragtag.py correct GCA_025200525.1_XYYC_v1.0_genomic.fna graph_prefix.contig -t 8
Mon Mar 20 02:23:52 2023 --- WARNING: Without '-u' invoked, some component/object AGP pairs might share the same ID. Some external programs/databases don't like this. To ensure valid AGP format, use '-u'.
Mon Mar 20 02:23:52 2023 --- INFO: Mapping the query genome to the reference genome
Mon Mar 20 02:23:52 2023 --- INFO: Running: minimap2 -x asm5 -t 8 /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/GCA_025200525.1_XYYC_v1.0_genomic.fna /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/graph_prefix.contig > /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/ragtag_output/ragtag.correct.asm.paf 2> /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/ragtag_output/ragtag.correct.asm.paf.log
Mon Mar 20 02:57:53 2023 --- INFO: Finished running : minimap2 -x asm5 -t 8 /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/GCA_025200525.1_XYYC_v1.0_genomic.fna /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/graph_prefix.contig > /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/ragtag_output/ragtag.correct.asm.paf 2> /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/ragtag_output/ragtag.correct.asm.paf.log
Mon Mar 20 02:57:53 2023 --- INFO: Reading whole genome alignments
Mon Mar 20 03:03:40 2023 --- INFO: Filtering and merging alignments

**Now, ragtag.correct.asm.paf.log file show:**
[M::mm_idx_gen::42.970*1.63] collected minimizers
[M::mm_idx_gen::47.480*2.12] sorted minimizers
[M::main::47.480*2.12] loaded/built the index for 790 target sequence(s)
[M::mm_mapopt_update::50.858*2.05] mid_occ = 456
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 790
[M::mm_idx_stat::53.175*2.00] distinct minimizers: 116480354 (72.38% are singletons); average occurrences: 2.582; average spacing: 9.974; total length: 2999357698
[M::worker_pipeline::197.804*6.16] mapped 15625000 sequences
[M::worker_pipeline::334.103*6.92] mapped 15625000 sequences
[M::worker_pipeline::463.596*7.23] mapped 15625000 sequences
[M::worker_pipeline::571.906*7.38] mapped 15625000 sequences
[M::worker_pipeline::686.284*7.49] mapped 15625000 sequences
[M::worker_pipeline::784.104*7.56] mapped 15625000 sequences
[M::worker_pipeline::880.383*7.62] mapped 15625000 sequences
[M::worker_pipeline::1007.596*7.67] mapped 15625000 sequences
[M::worker_pipeline::1110.450*7.70] mapped 15625000 sequences
[M::worker_pipeline::1192.208*7.73] mapped 15454323 sequences
[M::worker_pipeline::1269.174*7.75] mapped 15151516 sequences
[M::worker_pipeline::1326.733*7.76] mapped 15151516 sequences
[M::worker_pipeline::1380.837*7.77] mapped 15151516 sequences
[M::worker_pipeline::1435.037*7.79] mapped 14992998 sequences
[M::worker_pipeline::1486.932*7.80] mapped 14705883 sequences
[M::worker_pipeline::1530.114*7.81] mapped 14705883 sequences
[M::worker_pipeline::1580.701*7.82] mapped 14403057 sequences
[M::worker_pipeline::1621.586*7.82] mapped 14285715 sequences
[M::worker_pipeline::1661.778*7.83] mapped 13977149 sequences
[M::worker_pipeline::1697.056*7.84] mapped 13810620 sequences
[M::worker_pipeline::1729.013*7.84] mapped 13513514 sequences
[M::worker_pipeline::1757.544*7.85] mapped 13186944 sequences
[M::worker_pipeline::1784.277*7.85] mapped 12873206 sequences
[M::worker_pipeline::1809.206*7.86] mapped 12506954 sequences
[M::worker_pipeline::1831.128*7.86] mapped 12090442 sequences
[M::worker_pipeline::1851.374*7.87] mapped 11686167 sequences
[M::worker_pipeline::1869.626*7.87] mapped 11215552 sequences
[M::worker_pipeline::1886.871*7.87] mapped 10713980 sequences
[M::worker_pipeline::1901.706*7.88] mapped 10210357 sequences
[M::worker_pipeline::1917.102*7.88] mapped 9686066 sequences
[M::worker_pipeline::1934.439*7.89] mapped 9168489 sequences
[M::worker_pipeline::1953.419*7.89] mapped 8662996 sequences
[M::worker_pipeline::1970.988*7.89] mapped 8194019 sequences
[M::worker_pipeline::1980.876*7.90] mapped 7936508 sequences
[M::worker_pipeline::1990.096*7.90] mapped 7936508 sequences
[M::worker_pipeline::2001.172*7.91] mapped 7852853 sequences
[M::worker_pipeline::2011.130*7.91] mapped 7066059 sequences
[M::worker_pipeline::2021.035*7.91] mapped 6136695 sequences
[M::worker_pipeline::2027.829*7.91] mapped 5248202 sequences
[M::worker_pipeline::2034.097*7.92] mapped 4269483 sequences
[M::worker_pipeline::2038.054*7.92] mapped 3085097 sequences
[M::worker_pipeline::2039.895*7.91] mapped 1251117 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -x asm5 -t 8 /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/GCA_025200525.1_XYYC_v1.0_genomic.fna /home/xiehaoxing/surveyworkxhx/youcha_survey/zuzhuang/ref_zuzhuang/graph_prefix.contig
[M::main] Real time: 2040.596 sec; CPU: 16145.971 sec; Peak RSS: 11.273 GB

**and ragtag.correct.err file has no content.**

Please help me! Thank you very much!

**Comment by yangxinzhi** [comment]
I have also encountered the same problem and I would like to ask how long it will take to run with -t 40 in patch.
nohup ragtag.py correct ~/gerbil/genome/GCF_000001635.27_GRCm39_genomic.fna ~/gerbil/genome_BIBU/GCA_004026785.1_MerUng_v1_BIUU_genomic.fna -t 50 -o ~/gerbil/genome_BIBU/ -u >~/gerbil/genome_BIBU/BILL_gerbil.log &   This is the command I used to run correct when I ran one last time it was over so quickly, why is it taking him so long this time

**Comment by link-xhx** [comment]
Hello! yangxinzhi. My program has been running for 20 days but it is not over yet
. May we can discuss this issue in more detail, please add my Wechat: Link-xhx.

**Comment by stachyris** [comment]
Hi both, 

Did you folks figure out this issue?
I am also facing this. Let me know, 

Thanks, 
Vinay

**Comment by link-xhx** [comment]
Hi, Vinay! At present, I have not solved this problem, I will continue to work hard, if I have a solution in the future, I will write here.
