### ISSUE TITLE
Higher confidence score with Ragtag than Ragoo

### ISSUE THREAD

**Issue by fanzhen199156** [malonge/RagTag#20]
Hi Micheal,
Did you use different formulas to calculate confidence scores with Ragtag from Ragoo?
In general, I observed much higher scores with Ragtag using the same data.
Thanks,
Zhen

**Comment by malonge** [comment]
Hi there,

The calculation is exactly the same as RaGOO and as described in the [paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-019-1829-6).

The difference is how the alignments are filtered. There are two differences in RagTag compared to RaGOO.

1. Unique alignments are retained, even if they are small (unless one invokes `--remove-small`)
2. Concordant alignments are merged together. This can be controlled with `-d`.

In all of our tests, these steps really improve scaffolding.

Thanks

**Comment by fanzhen199156** [comment]
Thank you!
