### ISSUE TITLE
A conflict occured when installing ragtag.

### ISSUE THREAD

**Issue by YunxinFan** [malonge/RagTag#22]
hello,
  when  I used the following command:
`conda install -c bioconda ragtag`
 a problem occured like this

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__cuda==10.1=0
  - feature:|@/linux-64::__cuda==10.1=0

Your installed version is: 10.1
how can I solve the conflict??
thank you very much.

**Comment by malonge** [comment]
Hi there,

There seems to be something going on with your conda environment and I am not experienced enough with conda to help you debug. Are you able to install with the [other installation options](https://github.com/malonge/RagTag/wiki/Installation)?

**Comment by YunxinFan** [comment]
Hi，

I have installed the RagTag with the other installtion options successfully,thanks for your reply.
