### ISSUE TITLE
Unable to update gff

### ISSUE THREAD

**Issue by ishengtsai** [malonge/RagTag#23]
Hi,

I tried to update gff using RagTag v1.0.1 but was unfortunately unsuccessful. I was wondering if there's any tips that I can advance please? I have scaffolded successfully and both agp and gff look okay.

Best,
Jason

`Thu Sep  3 14:53:03 2020 --- RagTag v1.0.1
Thu Sep  3 14:53:03 2020 --- CMD: /home/ijt/.local/bin/ragtag_update_gff.py test.gff ragtag_output/ragtag.scaffolds.agp
Traceback (most recent call last):
  File "/home/ijt/.local/bin/ragtag_update_gff.py", line 162, in <module>
    main()
  File "/home/ijt/.local/bin/ragtag_update_gff.py", line 156, in main
    sup_update(gff_file, agp_file)
  File "/home/ijt/.local/bin/ragtag_update_gff.py", line 114, in sup_update
    raise ValueError("Inconsistent input files.")
ValueError: Inconsistent input files.
`

**Comment by malonge** [comment]
Hi there,

Can you share the command used to generate your scaffolds (`ragtag.py scaffold ...`). Does `test.gff` refer to the same query assembly used for scaffolding?

Thanks

**Comment by ishengtsai** [comment]
Hi !

Apologise for not reading the manual properly. I thought it was the other way round, where the **reference** annotation can be transferred to query assembly. Really sorry for the inconvenience that have caused.

I will close this issue but this feature (transfer annotations) would be great if it's between closely related species / strains. 

Best,
Jason

**Comment by malonge** [comment]
Hi there,

I reccomend you use [liftoff](https://github.com/agshumate/Liftoff) for that task.

Thanks,
Mike

**Comment by juusotas** [comment]
For anyone else Googling for this issue with update gff, It seems that updategff expects gff files with one comment (# )line.
