### ISSUE TITLE
Paramater suggestions?

### ISSUE THREAD

**Issue by plattsad** [malonge/RagTag#25]
Hi.  I used Ragtag for the first time today and it seemed to work nicely.  I have a small 200MB (ish) genome that should be structurally very close to a high quality reference assembly I'm correcting relative to.  

There are two evident inversions that long read data suggests are artifacts.     Ragtag corrected the peritelomeric one with just the vanilla command-line, but the more centromeric-looking inversion is still there after running the commands below.  I wonder if anyone could suggest a tweak to the command line that might get both corrected?  Currently I'm just using:

```
ragtag.py correct 2017.fa 2020.fa -o correct_genome_only/ -t 12
ragtag.py scaffold 2017.fa ./correct_genome_only/2020.corrected.fasta  -o corrected_scaffolded_genome -t 12
```

Attaching a synmap of before/after, although I'd note that scaffold order is slightly rearranged between the two.
![RagTag](https://user-images.githubusercontent.com/66926484/92513875-fee9f280-f1de-11ea-90fe-918aa1873e06.png)

**Comment by malonge** [comment]
Hi there,

Inversions are a special case where a part of the filtered contig alignment will show up in the opposite strand, and that should always trigger a break. If the contig was not broken, that means that the filtered alignments are somehow missing that opposite-strand alignment. This could happen if, for example, the mapq score is lower than 10 for all alignments of the inversion. 

Do you know which contig contains this false inversion? If so, we can look at the alignments for that contig before and after filtering and merging. For this, you would have to rerun with `--debug`.

You could also just try to take a guess and lower `-f` or `-q` and see if that works. This may lower the over-all accuracy, though. You could also try reruning with Nucmer (`--aligner /path/to/nucmer`), especially since your genome is smaller. 

Thanks

**Comment by malonge** [comment]
If you can figure out which contig contains the inversion, here are the instructions for how to check what is going on with the alignments. Let's assume that the contig containing the inversion is `contig_x`.

Rerun ragtag correction like so:

`ragtag.py correct --debug 2017.fa 2020.fa -o correct_genome_only/ -t 12`

Then, in `correct_genome_only`, you will see a bunch of PAF files for debugging (`ragtag.correction.debug.*.paf`). For each of those PAF file, grep for the contig and sort by query position. For example:

`grep "contig_x" ragtag.correction.debug.merged.paf | sort -k3,3n -k4,4n`

Then, if you share the results for each PAF file here, it should be clear why the inversion wasn't broken.

**Comment by plattsad** [comment]
Hi Michael.  Thanks for the rapid feedback. The two syntenic chromosomes here would be Fvb4 (in the reference) and lcl|tig00000001 (in the query).    Just greping out Fvb1 from ragtag.correction.debug.merged.paf suggests that the aligner isn't seeing anything from the inversion post-filtering:

lcl|tig00000001	29985601	583	12716659	+	lcl|Fvb4	33907851	309	6367357	4502805	6367048	35
lcl|tig00000018	125612	64974	65038	-	lcl|Fvb4	33907851	7861052	7861116	64	64	39
lcl|tig00000019	322920	8739	320527	-	lcl|Fvb4	33907851	7861052	7861116	64	64	39
lcl|tig00000020	89479	75669	75733	-	lcl|Fvb4	33907851	7861052	7861116	64	64	39
lcl|tig00000020	89479	6932	7010	-	lcl|Fvb4	33907851	15900266	15900344	78	78	50
lcl|tig00000028	186963	21453	170831	-	lcl|Fvb4	33907851	18598436	18598565	95	129	59
lcl|tig00000020	89479	3646	3704	-	lcl|Fvb4	33907851	22003813	22003871	58	58	25
lcl|tig00000020	89479	383	596	+	lcl|Fvb4	33907851	27007992	27008231	74	254	23
lcl|tig00000006	3978700	5	3978375	+	lcl|Fvb4	33907851	29894482	33907774	1733972	4013292	14
lcl|tig00000035	77833	77017	77318	+	lcl|Fvb4	33907851	33907129	33907422	55	301	11

If I go to look at the unfiltered alignments and plot + strand as red (+) and - strand as green (x), then I can just about make out the inversion, but its pretty noisy compared to the synmap (which uses CDS alignments + dagChaining).  So, I think I'll maybe try nucmer at this point per your suggestion as I'm not sure with this much noise that it makes sense to lower the filtering criteria.
![Ragtag_Fvb4](https://user-images.githubusercontent.com/66926484/92602012-8f761080-f27b-11ea-91f6-8bd7274d6ee8.png)

**Comment by malonge** [comment]
Hi there,

The merged paf file confirms that the raw negative strand alignments are filtered for some reason. Alignments are filtered by mapq (<10 by default) or unique alignment length (`-f`). Can you look in the raw PAF and see if there is at least one negative-strand alignment in the approximate inversion location with a mapq score >= 10? If so, then `-f` would be the parameter to focus on. And yes, perhaps Nucmer will work better here as well. 

Unfortunately, if none of these tips work, you may have to manually correct the inversion. I can also help you will that if needed.

Thanks

**Comment by plattsad** [comment]
Right - I'm seeing a lot of what look like strong negative strand alignments in that region (starred lines in the below, should be approx Fvb4 17.3MBase - 20.3MBase) with block lengths from 100Kbase to 700Kbase and MAPQ ~60.   So perhaps a little unclear why these don't make it past the filtering stage.

`lcl|tig00000001	29985601	1619068	1620670	-	lcl|Fvb4	33907851	1676881	1678316	316	1603	60	
lcl|tig00000001	29985601	24459605	24460140	-	lcl|Fvb4	33907851	2950220	2950757	134	573	60	
lcl|tig00000001	29985601	23801241	23801474	-	lcl|Fvb4	33907851	6341634	6341866	78	233	53	
lcl|tig00000001	29985601	6330202	6333636	-	lcl|Fvb4	33907851	6373874	6377359	2498	3485	60	
lcl|tig00000001	29985601	8582624	8582888	-	lcl|Fvb4	33907851	9258891	9259158	76	267	32	
lcl|tig00000001	29985601	8582103	8582560	-	lcl|Fvb4	33907851	9261485	9262000	158	515	31	
lcl|tig00000001	29985601	13441426	13443202	-	lcl|Fvb4	33907851	10160880	10162743	495	1887	36	
lcl|tig00000001	29985601	17963311	17964396	-	lcl|Fvb4	33907851	10225582	10226639	120	1091	38	
lcl|tig00000001	29985601	9641322	9642477	-	lcl|Fvb4	33907851	10854701	10855870	219	1172	60	
lcl|tig00000001	29985601	10079568	10085007	-	lcl|Fvb4	33907851	12009590	12014897	2684	5471	60	
lcl|tig00000001	29985601	10131895	10132515	-	lcl|Fvb4	33907851	12427155	12427796	76	641	29	
lcl|tig00000001	29985601	10112001	10112527	-	lcl|Fvb4	33907851	12428543	12429071	83	528	54	
lcl|tig00000001	29985601	13404345	13404801	-	lcl|Fvb4	33907851	12700421	12700884	200	464	53	
lcl|tig00000001	29985601	10656428	10656605	-	lcl|Fvb4	33907851	13225933	13226113	66	180	26	
lcl|tig00000001	29985601	10332033	10332348	-	lcl|Fvb4	33907851	13538330	13538645	160	316	60	
lcl|tig00000001	29985601	12205054	12213229	-	lcl|Fvb4	33907851	13585802	13594061	1280	8313	35	
lcl|tig00000001	29985601	28567378	28572462	-	lcl|Fvb4	33907851	13866090	13871248	2996	5163	43	
lcl|tig00000001	29985601	10149823	10150484	-	lcl|Fvb4	33907851	13961488	13962190	139	702	42	
lcl|tig00000001	29985601	13549497	13550122	-	lcl|Fvb4	33907851	14254769	14255409	273	640	44	
lcl|tig00000001	29985601	10359722	10360084	-	lcl|Fvb4	33907851	16327661	16328019	143	387	24	
lcl|tig00000001	29985601	20252374	20575861	-	lcl|Fvb4	33907851	17420223	17747001	270328	326951	60	*
lcl|tig00000001	29985601	20081465	20243372	-	lcl|Fvb4	33907851	17745690	17903502	130081	163823	60	*
lcl|tig00000001	29985601	26592413	26592977	-	lcl|Fvb4	33907851	17873633	17874189	181	575	30	*
lcl|tig00000001	29985601	20040856	20081421	-	lcl|Fvb4	33907851	17905729	17951816	34161	46158	60	*
lcl|tig00000001	29985601	20028169	20031701	-	lcl|Fvb4	33907851	17951892	17955638	2464	3752	60	*
lcl|tig00000001	29985601	19991697	20028158	-	lcl|Fvb4	33907851	17968179	18004857	33510	36691	60	*
lcl|tig00000001	29985601	19991252	19991686	-	lcl|Fvb4	33907851	18007076	18007510	434	434	60	*
lcl|tig00000001	29985601	19726503	19982204	-	lcl|Fvb4	33907851	18007524	18267478	202393	260398	60	*
lcl|tig00000001	29985601	19726419	19726482	-	lcl|Fvb4	33907851	18268158	18268221	63	63	30	*
lcl|tig00000001	29985601	19052355	19726352	-	lcl|Fvb4	33907851	18279990	18974643	569249	699817	60	*
lcl|tig00000001	29985601	18638917	19043259	-	lcl|Fvb4	33907851	18974649	19393680	316999	419126	60	*
lcl|tig00000001	29985601	28568579	28575125	-	lcl|Fvb4	33907851	19328581	19335229	2004	6669	60	*
lcl|tig00000001	29985601	18616123	18638786	-	lcl|Fvb4	33907851	19396037	19419146	11900	23129	60	*
lcl|tig00000001	29985601	18614138	18615483	-	lcl|Fvb4	33907851	19417789	19419146	538	1357	38	*
lcl|tig00000001	29985601	18465809	18613501	-	lcl|Fvb4	33907851	19417789	19567826	104502	150061	60	*
lcl|tig00000001	29985601	17986932	18465725	-	lcl|Fvb4	33907851	19577618	20062748	372831	485609	60	*
lcl|tig00000001	29985601	10360985	10362937	-	lcl|Fvb4	33907851	19732280	19734227	894	1984	41	*
lcl|tig00000001	29985601	17534991	17926168	-	lcl|Fvb4	33907851	20062772	20458292	321971	395712	60	*
lcl|tig00000001	29985601	17934961	17935222	-	lcl|Fvb4	33907851	20064941	20065202	188	262	60	*
lcl|tig00000001	29985601	28272472	28272622	-	lcl|Fvb4	33907851	24830515	24830666	119	151	44	
lcl|tig00000001	29985601	17969084	17970660	-	lcl|Fvb4	33907851	24978300	24980156	248	1891	37	
lcl|tig00000001	29985601	10358425	10359925	-	lcl|Fvb4	33907851	28667252	28668854	492	1621	60	`

**Comment by malonge** [comment]
Hi there,

This should mean that these alignments are not passing the unique anchor filtering. I can verify this if you provide a PAF file. You can either provide the whole raw PAF file or just the PAF lines for `lcl|tig00000001`. I do need every alignment for that contig, not just the inversion alignments, since that is needed for unique anchor filtering.

Thanks,
Mike

**Comment by malonge** [comment]
In a separate thread, we determined that these alignments were being removed since they were contained after merging. It seems like adding the `-f 10000 --remove-small` parameters worked since that filtered out repeat alignments that was causing the containment and were not removed during the standard repeat filtering. 

It looks like I also need to re-consider how alignments are merged. Right now they need to be with `-d` bp of each other with respect to the reference. But I may consider also requiring that they need to be with `-d` bp of each other with respect to the query.
