### ISSUE TITLE
Can this be used to construct exome assembly

### ISSUE THREAD

**Issue by Admera2020** [malonge/RagTag#26]
Hello, 

I have a unique situation where we have reads from WES and interested in only a subset of genes. I was wondering if RagTag would be appropriate to assemble contigs for the small set of genes. 

Best,

**Comment by malonge** [comment]
Hi there,

If I understand your question, I don't think ragtag would be suitable here. First of all, ragtag does not do any assembly at all. You will have to use a different tool for that. And given contigs, ragtag just orders and orients contigs according to a reference. I suppose that could be useful in some cases here but it seems like that is not what you are after.

Thanks

**Comment by Admera2020** [comment]
Thanks for the quick response. Sorry, you are right, I completely miss-understood the concept.
