### ISSUE TITLE
Requiring specific mapping segment lengths

### ISSUE THREAD

**Issue by selasphoruskershaw** [malonge/RagTag#32]
Hi @malonge ,

I am wondering if there is a way to require a minimum mapping segment length of 10kb for scaffolds shorter than 1 Mbp, and to require a mapping segment length of at least 50kb for scaffolds longer than 1 Mbp.

Is there also a way I can ensure that half of the alignment segments per scaffold align to the same chromosomes (I know that I can interpret the confidence score to enforce the requirement that more than half of the total scaffold length aligns to the same chromosome).

Also, is there a way to import a mashmap outfile and use that instead of what minimap2 produces? I would like to compare the results of each if possible.

Thanks for your help!

**Comment by malonge** [comment]
Hi there,

>Is there also a way I can ensure that half of the alignment segments per scaffold align to the same chromosomes

You can do this by setting `-i 0.5`, though it should be interpreted slightly differently. This will ensure that of all the reference bases covered by alignments to a given query contig, at least half of them will be on the same chromosome.

>Also, is there a way to import a mashmap outfile and use that instead of what minimap2 produces? I would like to compare the results of each if possible.

While there is no automatic way to do this, RagTag can be made to run with any [PAF](https://github.com/lh3/miniasm/blob/master/PAF.md) (or delta) file because RagTag won't overwrite preexisting intermediate files (unless prompted to do so with `-w`). The following shows an example of how to do this:

```
mkdir ragtag_output
cd ragtag_output
ln -s /path/to/mashmap.paf query_against_ref.paf
cd ..
ragtag.py scaffold ref.fa query.fa
```

If you are using a delta file instead, set `--aligner nucmer`.


>I am wondering if there is a way to require a minimum mapping segment length of 10kb for scaffolds shorter than 1 Mbp, and to require a mapping segment length of at least 50kb for scaffolds longer than 1 Mbp.

First of all, in general, if you want to impose a strict length filter, set `--remove-small`. Otherwise, small but unique alignments will be retained. For example, to remove all alignments shorter than 10kbp, you should set `-f 10000 --remove-small`.

There is no automatic way to have variable length cutoffs like you describe. You could hack it by filtering the alignments yourself and using the filtered PAF/delta for ragtag (same reasoning as the second answer).

Thanks,
Mike

**Comment by selasphoruskershaw** [comment]
Thank you for your help, this mostly worked as needed!

However, when I did the commands to use my mashmap file, the program output the same thing as it did with minimap2. I'm not sure how possible it is for both programs to output the exact same thing, but it seems unlikely.

**Comment by malonge** [comment]
There are a few things we can do to ensure that ragtag is using the correct alignment file.

Firstly, please share your command and the logging to stderr.

Secondly, you can run ragtag with `--debug` which will produce a bunch of intermediate PAF files. You can run ragtag once with minimap2 and once with your mashap file and compare the intermediate PAF output files to ensure they are different. I suggest using `-o` to give each its own output directory in order to keep things separate.

**Comment by selasphoruskershaw** [comment]
Hello,

Thanks for all of your previous help using RaGoo and Ragtag, and I hope you
had a great holiday and New Year. My variant calling just finished, and I
noticed in my vcf file that my data is still in contig form-it does not
appear to be assigned to chromosomes. Was ragtag supposed to do this, or
was I supposed to have assigned chromosome labeling and ordering manually
somehow?

I also noticed that when I did data filtering, most of my data disappeared
when applying filters (I went from a 32 gb to a 9 kb file when applying a
--max-missing filter of 0.85 in vcftools). When I applied the same command
to the original dataset, the correct vcf file size of ~3 gb was created.

Are either of these problems issues you are familiar with? I'd appreciate
any help I can get.

Thanks,
Brian

**Comment by malonge** [comment]
Hi Brian,

Hopefully we can address what is going on. Can you share the full command and the logging output by ragtag? Can you also briefly describe what you used for the reference and query assemblies. The short answer is that RagTag will automatically order and orient query contigs and assign them to their corresponding reference sequence. 

I am not sure I know what your second question is referring to. Which data filtering is this, exactly?

Thanks,
Mike

**Comment by selasphoruskershaw** [comment]
Thanks for your response.

For question 1)
The command I used was "ragtag.py scaffold -f 10000 --remove-small barn.fna
flycatcher.fna". The only log file I found was
"query_against_ref.paf.log"-I've pasted the contents below. My reference
genome is only assembled to scaffold level, so my goal was to align the
reference genome (barn swallow) to a relative (the flycatcher) to assign
scaffolds to chromosomes. Links to those genomes are also pasted below.
Next, I aligned my genomic data to my barn swallow reference so that I have
data to work with where scaffolds are assigned to chromosomes. The
resultant vcf file was 33.32 gb and it appears that only scaffold
information is available, matching my original data.

Log file:
[M::mm_idx_gen::25.498*1.00] collected minimizers
[M::mm_idx_gen::37.061*1.00] sorted minimizers
[M::main::37.061*1.00] loaded/built the index for 21428 target sequence(s)
[M::mm_mapopt_update::38.721*1.00] mid_occ = 100
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 21428
[M::mm_idx_stat::39.423*1.00] distinct minimizers: 95698760 (94.18% are
singletons); average occurrences: 1.578; average spacing: 7.404
[M::worker_pipeline::73.520*1.00] mapped 176 sequences
[M::worker_pipeline::101.439*1.00] mapped 48 sequences
[M::worker_pipeline::111.315*1.00] mapped 140 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x asm5 -t 1
/media/escordato/data_24tb/Brian/ragtag/flycatcher.fna
/media/escordato/data_24tb/Brian/ragtag/barn.fna
[M::main] Real time: 111.375 sec; CPU: 111.373 sec; Peak RSS: 4.787 GB

Flycatcher genome: https://www.ncbi.nlm.nih.gov/assembly/GCF_000247815.1/

Barn swallow genome: https://www.ncbi.nlm.nih.gov/assembly/GCA_003692655.1/

For question 2)
After doing variant calling of my data aligned to the mapped barn swallow
genome (from above), I then went on to do some filtering in VCFtools for
data quality. I filtered to allow 15% missing data (--max-missing 0.85 in
vcftools) and the size of the VCF file dropped from 33.32 gb to 9kb. When I
applied the same filter to another vcf of the same data (data aligned to
the original barn swallow genome where scaffolds were not mapped to the
flycatcher genome) the VCF file size was about 3 gb. I am wondering what I
did to achieve such a discrepancy-the only difference in methodology I
applied was assigning the barn swallow genome scaffolds to chromosomes
using the flycatcher in ragtag.

I'd appreciate any help-I'm pretty lost.

Thanks again,
Brian

**Comment by malonge** [comment]
Hi Brian,

I could be wrong, but it may be the case that you need to switch the order of those assemblies. From what I can tell, the "reference" here should be the more contiguous, chromosome scale flycatcher assembly. Then, the assembly that you want to scaffold (the query) would be the barn swallow genome.

If that is correct, then the command should be as follows:

```
ragtag.py scaffold -f 10000 --remove-small flycatcher.fna barn.fna
```

This might be a result from the fact that RaGOO had the opposite ordering, so this is a backwards incompatibility with RagTag.

As far as variant calling, am I correct that you want to call variants in the ragtag barn swallow scaffolds with respect to the flycatcher assembly?

Thanks,
Mike

**Comment by selasphoruskershaw** [comment]
Thank you! I will give that a shot for the first question.

For the second question, I have whole genome data for several different
swallow species, and I am calling variants for them after aligning them to
the barn swallow genome with scaffolds mapped to the flycatcher genome
using ragtag. Does that make sense? Sorry for the confusion.

**Comment by malonge** [comment]
Hi there,

I think I understand. Here is how I will summarize it:

1. Build barn swallow chromosomes with `ragtag scaffold`
**Input**:    Flycatcher chromosomes (ref) and barn swallow scaffolds (query)
**Output**: barn swallow chromosomes

2. Call variants in a barn swallow population. For each barn swallow sample:
**Input**: Barn swallow chromosomes (from ragtag)(ref) and another barn swallow sample (query)
**output**: variant calls

If that is correct, then rerun ragtag as I have suggested and then I think you will be on track. 

Thanks,
Mike

**Comment by selasphoruskershaw** [comment]
Thanks again. I will give this a shot and let you know if the issues are
resolved!

**Comment by selasphoruskershaw** [comment]
Quick question-all of the output files still list the scaffolds, (QRBIOxxx
mostly), and there isn't a named chromosome anywhere that I can see. This
looks like similar output as last time (I think I actually used the same
command before-"ragtag.py scaffold -f 10000 --remove-small -i 0.5
flycatcher.fna barn.fna"-I just wrote it in the wrong order in my question
yesterday). Should the ragtag output list the actual chromosomes the
scaffolds are actually aligned to somewhere? I want to ensure things are
correct before initiating the time-consuming process of variant calling.
Thank you!

**Comment by malonge** [comment]
Hi there,

I ran ragtag on my end and got the following stats:

```
$ cat ragtag.scaffolds.stats
placed_sequences  placed_bp   unplaced_sequences  unplaced_bp  gap_bp  gap_sequences
134               1085561472  230                 128182407    8200    82
```

So that means that about 90% of the sequences were ordered and oriented, which is decent. Here is what the AGP looks like:

```
$ head ragtag.scaffolds.agp
## agp-version 2.1
# AGP created by RagTag
AGTO02008653.1_RagTag	1	721187	1	W	QRBI01000249.1	1	721187	+
CM001988.1_RagTag	1	177757	1	W	QRBI01000181.1	1	177757	+
CM001988.1_RagTag	177758	177857	2	U	100	scaffold	yes	align_genus
CM001988.1_RagTag	177858	580794	3	W	QRBI01000276.1	1	402937	+
CM001988.1_RagTag	580795	580894	4	U	100	scaffold	yes	align_genus
CM001988.1_RagTag	580895	1067707	5	W	QRBI01000227.1	1	486813	-
CM001988.1_RagTag	1067708	1067807	6	U	100	scaffold	yes	align_genus
CM001988.1_RagTag	1067808	1360381	7	W	QRBI01000224.1	1	292574	-
```

`CM001988.1` is the first chromosome of the flycatcher assembly, so `CM001988.1_RagTag` would be the corresponding chromosome for barn swallow. In case it helps, here is the [file format specification](https://www.ncbi.nlm.nih.gov/assembly/agp/AGP_Specification/).

Did you get the same results as me?

**Comment by selasphoruskershaw** [comment]
I'm not getting the CM001988.1_Ragtag headings...I'm getting
"NC_021671.1_Ragtag for the first part of the first column, then QRBIO. I'm
super confused at what I did wrong? Can I see the exact command you used? I
assume we also used the same fna files?

**Comment by malonge** [comment]
Looks like I used the GenBank assemblies while you are using the RefSeq assemblies. It shouldn't make a difference though, `NC_021671.1` is also chromosome 1 (but that is the refseq header). Do your stats look the same as mine?

**Comment by selasphoruskershaw** [comment]
Here are my first few lines of my .agp file. I also had 89% of sequences
ordered/oriented.

## agp-version 2.1
# AGP created by RagTag
NC_021671.1_RagTag 1 177757 1 W QRBI01000181.1 1 177757 +
NC_021671.1_RagTag 177758 177857 2 U 100 scaffold yes align_genus
NC_021671.1_RagTag 177858 580794 3 W QRBI01000276.1 1 402937 +
NC_021671.1_RagTag 580795 580894 4 U 100 scaffold yes align_genus
NC_021671.1_RagTag 580895 1067707 5 W QRBI01000227.1 1 486813 -
NC_021671.1_RagTag 1067708 1067807 6 U 100 scaffold yes align_genus
NC_021671.1_RagTag 1067808 1360381 7 W QRBI01000224.1 1 292574 -
NC_021671.1_RagTag 1360382 1360481 8 U 100 scaffold yes align_genus
NC_021671.1_RagTag 1360482 1671190 9 W QRBI01000200.1 1 310709 -
NC_021671.1_RagTag 1671191 1671290 10 U 100 scaffold yes align_genus
NC_021671.1_RagTag 1671291 98332910 11 W QRBI01000120.1 1 96661620 +
NC_021671.1_RagTag 98332911 98333010 12 U 100 scaffold yes align_genus
NC_021671.1_RagTag 98333011 113218135 13 W QRBI01000107.1 1 14885125 -
NC_021671.1_RagTag 113218136 113218235 14 U 100 scaffold yes align_genus
NC_021671.1_RagTag 113218236 121811007 15 W QRBI01000136.1 1 8592772 +

**Comment by malonge** [comment]
Great so everything looks normal to me. `NC_021671.1_RagTag` is basically the new chromosome 1 for the barn swallow sample.

**Comment by selasphoruskershaw** [comment]
Thank you!

So it looks like this file matches what I did initially-the previous fasta
file and the fasta file I produced this morning both have the NC_021686,
etc, chromosome alignments. However, the chromosome alignments disappear
when I do variant calling, and the resultant vcf only has scaffold-level
sequences (all QRBIOxxx). Do you have any suggestions on this?

**Comment by malonge** [comment]
Can you give an example command for the alignments that you are generating to call variants?

Should be something like this:

```
minimap2 -cx asm5 ragtag.scaffolds.fasta barn.sample_X.fasta
```

**Comment by malonge** [comment]
Also, any unplaced barn swallow scaffolds will keep their original scaffold headers. You can add `-u` to change that. According to the stats file, roughly 63% of scaffolds were unplaced. These are probably mostly smaller scaffolds.

**Comment by selasphoruskershaw** [comment]
Here are the steps I followed after using ragtag:

I didn't manually have any command for minimap-am I missing a step?

1) alignment of my data to the fasta file generated by ragtag: bwa mem -M
-t 8
2) merge the bam files generated by step 1)
3) variant calling of merged bam file: bcftools mpileup -a AD<DP,SP -Ou -f
<reference genome>

**Comment by malonge** [comment]
Can you share the exact bwa mem command you used?

**Comment by selasphoruskershaw** [comment]
I've attached the scripts I've used so you can take a closer look: here's
the bwa mem command:

bwa mem -M -t 8 \
$REF $FORWARD $REVERSE | samtools view -b | samtools sort -T $SAMPLE >
$OUTPUT_DIR/${SAMPLE}_sorted.bam

# bwa mem -M -t 16 \
# -R $READGROUP \
# $REF $FORWARD $REVERSE | samtools view -b | samtools sort -T ${SAMPLE} >
${WORKDIR}/${SAMPLE}_pe.bam

**Comment by malonge** [comment]
Which file specifically is $REF?

**Comment by selasphoruskershaw** [comment]
$REF should be ragtag.scaffolds.fasta (the fasta file output by ragtag)

**Comment by malonge** [comment]
Everything looks reasonable to me. I think you will need to look at the alignments to see why reads are not aligning to the chromosomes. It appears though that there is no issue with RagTag specifically, so I will close this for now. If you find that ragtag caused some sort of error, please reopen the issue.

Thanks
