### ISSUE TITLE
A discussion of correction module.

### ISSUE THREAD

**Issue by CAShuangchao** [malonge/RagTag#35]
hello

As it turned out, I was keen to understand what correction module would do to raw data, and therefore decided whether correct's steps were needed for my projects.
Notwithstanding the introduction's declaration that "In all cases, sequence is never added or subtracted. Query sequences are only broken at points of putative misassembly." I tested my data to find that the operation seemed to diminish the structural variation between Query and Reference. Specifically, if a large structural variation existed between the two genome, it would, after correct, diminish its difference, and even rectify Query to be the same as Reference. This introduces a great deal of bias in reference-guide assembly. 
My data were generated by pacbio-Hifi sequencing, and contigs was assembled using Canu, and the above conclusions were obtained from the test results of chromosome 6 in indica and japonica rice.
Looking forward to your reply.

Regards
huangchao

**Comment by malonge** [comment]
Hi Huangchao,

I hope my [note at the end of the correction wiki](https://github.com/malonge/RagTag/wiki/Correction#misassemblies-vs-true-variation) will help to answer some of these questions. Beyond what is stated there, I will say that, in my experience, HiCanu produces relatively few structural misassemblies, so you may choose to skip correction. You should at least use `-R` to use your hifi reads to validate potential breaks, though the sensitivity of this technique might need to be adjusted with command line parameters. I also have noticed that interchromosomal structural differences are more likely to be misassemblies than intrachromosomal differences. Granted I have never worked with rice data, but I rarely see the former type of SVs in my plant data, whereas things like inversions are quite common. So you may consider adding `--inter`. 

I also want to emphasize that it is indeed true that no query sequence is ever added, subtracted, or mutated. Correction only. impacts contiguity. You can perfectly reconstruct the query sequence from the `ragtag.correction.agp` file. 

Please let me know if you have any more questions or comments.

Thanks

**Comment by CAShuangchao** [comment]
> Hi Huangchao,
> 
> I hope my [note at the end of the correction wiki](https://github.com/malonge/RagTag/wiki/Correction#misassemblies-vs-true-variation) will help to answer some of these questions. Beyond what is stated there, I will say that, in my experience, HiCanu produces relatively few structural misassemblies, so you may choose to skip correction. You should at least use `-R` to use your hifi reads to validate potential breaks, though the sensitivity of this technique might need to be adjusted with command line parameters. I also have noticed that interchromosomal structural differences are more likely to be misassemblies than intrachromosomal differences. Granted I have never worked with rice data, but I rarely see the former type of SVs in my plant data, whereas things like inversions are quite common. So you may consider adding `--inter`.
> 
> I also want to emphasize that it is indeed true that no query sequence is ever added, subtracted, or mutated. Correction only. impacts contiguity. You can perfectly reconstruct the query sequence from the `ragtag.correction.agp` file.
> 
> Please let me know if you have any more questions or comments.
> 
> Thanks

**Comment by CAShuangchao** [comment]
Hello, malonge

I am very glad to receive your reply. I see what you mean. Ragtag is a great piece of software, just like its authors. Thank you and your team for your excellent work and thank you again for your guidance.

Sincerely 
huang Chao

**Comment by malonge** [comment]
Thanks - that is very kind of you.
