### ISSUE TITLE
Can i use mummer4 instead of the mummer3?

### ISSUE THREAD

**Issue by Zea1nfO** [malonge/RagTag#36]
Hi sir
  Just like the topic, the ragtag chooses the mummer3 by default, can i use mummer4 to replace it？
Thanks a lot.

**Comment by malonge** [comment]
Hi there,

I could be wrong, but I think it might work if you just point to the mummer4 executable with `--aligner`.  Worse case scenario, you can generate a delta file any way you like and then just plug it in to the ragtag output. If using mummer4 directly doesn't work, I can tell you how to do this.

**Comment by Zea1nfO** [comment]
Hi sir
  I try it as you said, it worked. Because the mummer4`s nucmer can set multi threads jobs, it is faster than before.

**Comment by malonge** [comment]
Thanks for verifying that! You are right that the ability to use Mummer4 is quite convenient.
