### ISSUE TITLE
understand the output file "ragtag.confidence.txt"

### ISSUE THREAD

**Issue by CAShuangchao** [malonge/RagTag#37]
Hello, malonge
    Sorry to bother you again, but Ragtag is a great tool with the advantages of both speed and precision. My question is to understand the output file "ragtag.confidence.txt", Why do some contig grouping_confidence,location_confidence and orientation_confidence have sizes that are out of sync or even far apart? that is, for example, grouping_confidence=1 but location_confidence or orientation_confidence may be 0.1 or lower. Because I didn't understand how they were calculated, I couldn't understand the difference between Query genome and Ref genome, and it was difficult to implement personalized parameters such as -i,-a, and -s in my project. 
    Ragtag is a really good software, especially for me who is a junior and not experienced in writing scripts. Thank you and your team again for your hard work on this software.

Sincerely,
huangchao

**Comment by CAShuangchao** [comment]
Hi, please forgive me for rashly asking questions without reading the paper carefully. This is not a good habit to solve questions, but thank you very much for replying so quickly. Now Beijing time is almost 0: 00, when I get up tomorrow, read the paper carefully and reply to you. Thank you again.



------------------ Original ------------------

**Comment by malonge** [comment]
I am happy to point you in the right direction, especially since there is so much information scattered about on GitHub and in the papers. Now that I am thinking about it, it might be wise to include this info in the GitHub wiki.

Thanks

**Comment by CAShuangchao** [comment]
Hi, the description of _Scaffolding confidence scores_ in paper is helpful, But there is one sentence that I am a little confused about: **"Finally, to calculate the orientation confidence, Each base pair in each alignment between a contig and its assigned reference chromosome casts a vote for the orientation of its alignment."** My understanding is that in this orientation and alignment, the base on the contig is the same as the base on the reference genome, so this base pair will vote in this direction; if these two bases are different, then they don't vote in this direction. Right?

Thanks
huangchao

**Comment by malonge** [comment]
Hi Huangchao,

It is not the case that only matching bases cast a vote. For each alignment, the alignment length is calculated as the reference start subtracted from the reference end position. Then, each alignment will cast that many votes for the strand of the alignment. Please let me know if this is still unclear.

Thanks,
Mike

**Comment by CAShuangchao** [comment]
Hi Mike,
Thank you very much for your reply, but to be honest, I still can't understand, which may be caused by my weak knowledge reserve. Could you be more specific? I'm really sorry for your time.

Thanks,
huangchao

**Comment by malonge** [comment]
No problem at all. I will provide an example. Lets consider the hypothetical query contig `contig_1`. Let's say that `contig_1` has a total of three alignments, all to the reference `chr1`. Here are three example alignments in [paf format](https://github.com/lh3/miniasm/blob/master/PAF.md).

```
contig_1    1000    0     10    +    chr1    5000000    500    510    9     10    60
contig_1    1000    20    40    +    chr1    5000000    520    540    18    20    60
contig_1    1000    60    65    -    chr1    5000000    560    565    5     5     60
```

The 11th column is the alignment length, which ragtag defines as column 9 - column 8. Using the alignment lengths, we have the following votes:

10 votes for +
20 votes for +
5 votes for -

So the contig would be assigned a positive strand (+) and it would have a confidence score of 

```
(10 + 20)/(10 + 20 + 5) = 0.857
```

**Comment by CAShuangchao** [comment]
Hi,
It's very kind of you. I know it in an instant. Really excellent software and responsible author, I am grateful and touched!


Thank you
Huang Chao






------------------ Original ------------------

**Comment by malonge** [comment]
Thanks, that is very kind of you. Feel free to reopen the issue if you have additional questions.
