### ISSUE TITLE
why the size of result is much bigger than the reference genome?

### ISSUE THREAD

**Issue by zzsunday** [malonge/RagTag#39]
hello,

I use the ragtag to do scaffold, my reference genome is 43M,  but the size of result is much bigger than the reference genome(the asssembled genome was 367M)  

Here was my command:
ragtag.py scaffold -r -u /public/agis/shaohaojing_group/sunda/rice-shanglianguang/reference_by_hzaurice/ZS97_RS3_chr1.fa \
/public/agis/shaohaojing_group/sunda/rice-shanglianguang/ragtag_output/ZC206.contig.corrected.fasta \
 --aligner /public/agis/panweihua_group/panweihua/tools/minimap2/minimap2 \
 --mm2-params '-x map-ont' \
 -o /public/agis/shaohaojing_group/sunda/rice-shanglianguang/ragtag_output

**Comment by malonge** [comment]
Hi there,

Can you share the contents of `ragtag.scaffolds.stats`. Am I correct in observing that your reference is only a single chromosome. RagTag will output every input sequence, adding a few gaps for padding. So the only additional sequence comes from gaps. Given that you did not use `-r`, all of the gaps will be 100 bp each.

**Comment by zzsunday** [comment]
Sure.  I can share the file.

yes, my reference is only a single chromosome.
[ragtag.zip](https://github.com/malonge/RagTag/files/5833061/ragtag.zip)

**Comment by malonge** [comment]
Thanks for sharing. I see now that you _did_ use `-r` which explains the `1142557` bp of gap sequence added by ragtag. The stats file indicates that the query sequnece (ZC206.contig.corrected.fasta) contained a total of `381365507 ` bp, so it makes sense that the output is greater than 43M (the output will be `381365507 + 1142557` bp ). 

I believe the problem is just that you are using a single chromosome as the reference but a whole genome assembly as the query. In general, it is advisable to align whole genomes to each other since this can avoid spurious contig placement. I believe that should solve your problem.

**Comment by zzsunday** [comment]
I have changed the reference to use the whole genome, and the size of result was almost the same as the reference.

Thank you.

**Comment by CAShuangchao** [comment]
Hi, malonge
Similar to this problem, sometimes if there is redundancy in query contigs, it is not possible to rely on Confidence scores to filter them out, so the final genome will be a little larger. These redundant sequences are usually less than 500KB, which may cause trouble to the subsequent analysis, so I would like to ask you:
1. Based on your project experience, can you recommend me some methods or software that can help me remove redundant sequences in the results generated by Canu?
2. In subsequent Ragtag updates, you could consider adding the function of removing redundant sequences and anchoring chromosomes, which might make Ragtag even more powerful.

Thank you
Huangchao

**Comment by malonge** [comment]
Hi @CAShuangchao,

I recommend using [purge dups](https://github.com/dfguan/purge_dups) for this. It is conceivable for RagTag to remove contigs that are contained within other contigs (with respect to the reference). Could you open up a new issue so that this is on my radar?

Thanks

**Comment by malonge** [comment]
Actually @CAShuangchao I just remembered that ragtag does have some checks to remove contained contigs. So in the new issue, maybe we can look at some test data to see why some redundant contigs are not removed.

**Comment by CAShuangchao** [comment]
Hi @malonge 
Thank you very much for your reply. Here is the test data for rice, in two folders, one represents the result of using purge dups  to remove the redundancy and the other is not to remove the redundancy sequence.They all run according to the "ragtag scaffold" default parameters. It does seem that Ragtag didn't filter out a lot of redundant sequences, but Purge Dups made it look much better. 
I would like to take this opportunity to ask you about it. In the above results of Purge Dups, I noticed that the location_confidence of some small contig was lower than 0.01. What happened? In fact, I consulted you about ragtag.confidence.txt last time, and you kindly demonstrated to me with an example how to obtain orientation confidence. However, I may be confused about the specific calculation rules of location_confidence at this time, so... Sorry to trouble you again.
[test_data.zip](https://github.com/malonge/RagTag/files/5837395/test_data.zip)

Thanks 
Huangchao

**Comment by CAShuangchao** [comment]
@malonge 
I'm really sorry. As for location_confidence, I did stare at the PAF file and calculated for a long time according to my own understanding, but I still couldn't get the same result. So please kindly demonstrate his operation rules, thank you.

**Comment by malonge** [comment]
Hi there @CAShuangchao,

Could I trouble you to open a new issue and copy these posts over?

Thanks,
Mike
