### ISSUE TITLE
Is there a way to run this as a batch?

### ISSUE THREAD

**Issue by Steven-Kemp** [malonge/RagTag#4]
Hi there,

When I attempt to write a small loop to run these one after the other, it will output to the same file and throw a number of errors. Is there a way to run the two scripts (correct and scaffold) on many samples at all?

Thanks!

**Comment by malonge** [comment]
Hi there,

If I understand the question right, you should be able to achieve this with the `-o` parameter. Just give each iteration a unique name and pass that to `-o` and the results for that specific iteration will be in a contained output directory.

Thanks

**Comment by Steven-Kemp** [comment]
Hi,

Yes, fixed my issue! Must have mistyped the -o option.

Thanks!
