### ISSUE TITLE
remove the redundancy sequence and understand location_confidence

### ISSUE THREAD

**Issue by CAShuangchao** [malonge/RagTag#40]
Hi @malonge
I am here. Here is the test data for rice, in two folders, one represents the result of using purge dups to remove the redundancy and the other is not to remove the redundancy sequence.They all run according to the "ragtag scaffold" default parameters. It does seem that Ragtag didn't filter out a lot of redundant sequences, but Purge Dups made it look much better.
I would like to take this opportunity to ask you about it. In the above results of Purge Dups, I noticed that the location_confidence of some small contig was lower than 0.01. What happened? In fact, I consulted you about ragtag.confidence.txt last time, and you kindly demonstrated to me with an example how to obtain orientation confidence. However, I may be confused about the specific calculation rules of location_confidence at this time, so... Sorry to trouble you again.

Thanks 
HuangChao
[test_data.zip](https://github.com/malonge/RagTag/files/5840174/test_data.zip)

**Comment by justdx** [comment]
Dear Mike and HuangChao,

I am reaching out to inquire whether the question has been resolved. In issue #39, Mike mentioned that RagTag includes certain checks to remove contained contigs. However, I am curious to understand how RagTag handles cases involving overlapped contigs.

I am currently using RagTag v2.1.0 to scaffold Arabidopsis contigs, and I have noticed that overlapped contigs are joined by Ns, as illustrated in case 1 below. Additionally, I have come across another scenario (case 2) where a contig (ctg2) is fully contained by two other contigs (ctg1 and ctg3), yet it still gets scaffolded into the assembly. I would appreciate some insights into how RagTag addresses such cases.

Thank you for your attention, and I look forward to your response.

![Picture 1](https://github.com/malonge/RagTag/assets/39363003/90a96768-f233-4b56-9ef7-ea1d84876e3e)

**Comment by malonge** [comment]
Hi there! Thanks for reaching out. The short answer is that overlaps and other redundancies should be taken care of prior to RagTag scaffolding. RagTag "scaffold" only orders and orients sequences — it does not merge them or remove them. 

RagTag "patch" however should remove redundant overlapping sequences when there is sufficient evidence.
