### ISSUE TITLE
Excluded query contigs are put in chr0

### ISSUE THREAD

**Issue by HenrivdGeest** [malonge/RagTag#42]
Thanks a lot for this easy to use and straightforward software.   I have a reference genome which consists of  chr1-10. My assembly has 100 contigs, plus a chloroplast contig. With your software I can tell via the '-j' parameter that it should not try to scaffold my chloroplast. That does work, without the parameter it get integrated somewhere on chromosome. However, with using the '-j' skip.txt file now my chloroplast contig is put into a chr0, as I want the unscaffolded contigs to be put into chr0 (using '-C').  Is it possible to run the software in such way that I get:
- anchored chromosomes in results fasta (already happening)
- a chr0 scaffold with all unplaced contigs in results fasta (already happening)
- my contigs which are listed in skip.txt, untouched and present in separate contigs in the result fasta?

**Comment by malonge** [comment]
Hi there,

Thanks for bringing this up. That should be straightforward to implement. I will add this new feature with v2.0.0, which I should be releasing within the next month. Perhaps you could do this manually in the meantime? Perhaps the easiest thing to do is separate the chloroplast contig prior to scaffolding, and then add it back in with the ragtag output.

Thanks

**Comment by HenrivdGeest** [comment]
Sure, I will do that in the meantime, thanks for looking into this!

**Comment by malonge** [comment]
Hi there,

This is now resolved since v2.0.0. You can use the `-J` to use this feature. thanks!
