### ISSUE TITLE
First-timer / Help with putting fastq or sam files into RagTag?

### ISSUE THREAD

**Issue by dgahmann** [malonge/RagTag#43]
Hello,

I am working on a reference-guided genome assembly project - my team was given Oxford Nanopore sequence reads that I merged into a single .fastq file and put through Minimap2 to get a single .sam file. My goal is to generate a consensus sequence in .fasta format that I can use for immediate sequence inspection and later annotation. However, I'm not sure where to go from here since I am totally new to coding and need guidance in getting started with RagTag. 

I understand that I have aligned my patient sample's sequence reads to my reference genome, but it looks like I need this to be in .fasta format... how to I enter the Minimap2 output (.sam) into the RagTag program? 

I also saw that Minimap2 is a sub-package of RagTag; maybe I'm confused because I am supposed to do the align the reads against the reference genome via the scaffolding function of RagTag instead of using Minimap2 separately? In that case, can I use my initial merged .fastq file in place of the query .fasta file? 

Thank you for the help!

**Comment by malonge** [comment]
Hi there,

Unfortunately, RagTag is for reference-guided scaffolding, not reference-guided assembly. So RagTag orders and orients genome assembly contigs via alignment to a reference genome.

Unfortunately, I don't know of any tools for reference-guided assembly with nanopore data.

Thanks

**Comment by dgahmann** [comment]
Hi Michael,

Thank you so much for the quick reply. This makes sense and I'm sorry I won't be able to use RagTag in my project! I appreciate the help.

**Comment by malonge** [comment]
Good luck!
