### ISSUE TITLE
Omni-C and Hi-C

### ISSUE THREAD

**Issue by ardy20** [malonge/RagTag#44]
Thanks a lot for your nice tool. I used it for scaffolding HiFi data using a Dovetail chromosome level assembly and it worked very well.

Could you please provide a step by step description or more details for Hi-C scaffolding? 

It is not clear how the .agp files must be prepared for the Hi-C scaffolding.

I mean in:   `ragtag.py merge -b hic.bam query.fasta out_*/*.agp `
How the files in `out_*/*.agp` must be prepared! 

Can we scaffold using Omni-C data instead of Hi-C?

Regards
Ardy

**Comment by malonge** [comment]
Hi Ardy,

I am glad to hear that this worked well for synteny scaffolding. RagTag `merge` is not a de novo Hi-C scaffolder. Instead, it is a scaffold merging tool that can utilize Hi-C to resolve merging conflicts. Please read more about this in [the docs](https://github.com/malonge/RagTag/wiki/merge), and open an issue if anything is unclear - those docs are new.

Suppose you have your Dovetail chromosome-level reference and Hi-C data. You could use do the following:

1. Run `ragtag.py scaffold dovtail_ref.fa query.fa`. This will yield an AGP file
2. Run SALSA2 or 3D-DNA, or some other Hi-C scaffolder to scaffold `query.fa` with you Hi-C data.

Then, if you see that the Hi-C scaffolds are not chromosome-scale or they have potential errors, you can try to merge those two AGP files together with `ragtag.py merge`, providing Hi-C alignments with `b`.

I am not familiar with Omni-C. Do they just use DNase for this? Or some other cocktail of restriction enzymes?

Thanks

**Comment by malonge** [comment]
Reading more about Omni-C, I think you will just want to use the "-r DNase" option.

**Comment by ardy20** [comment]
Thanks for your guide.
