### ISSUE TITLE
Merging of contig overlaps based on reference?

### ISSUE THREAD

**Issue by yusufmnx** [malonge/RagTag#46]
Greetings,

I'm looking to use RagTag to scaffold multi-contigs produced by de novo assemblies. However I found that contigs that had small but valid overlaps based on both the sequences themselves as well as per the reference genome used, were not merged but instead were scaffolded with a 100bp gap in between. Is there a way to merge them if the reference determines they should be so?

I've tested with -r (infer gap sizes), -g 1 (minimum inferred gap size = 1), -d 1 (alignment merge distance = 1) but to no avail.

Logfile is attached, with the query (HPUPM4.megahit.171220.fa) & reference (NC_045512.2_Wuhan-Hu-1_genome.fasta).
Thank you very much in advance.

[log.txt](https://github.com/malonge/RagTag/files/6048333/log.txt)
[query_and_ref.zip](https://github.com/malonge/RagTag/files/6048354/query_and_ref.zip)

**Comment by malonge** [comment]
Hi there,

RagTag orders and orients contigs but it does not merge or purge them. I recommend using purge_dups before using RagTag:

https://github.com/dfguan/purge_dups

Thanks
