### ISSUE TITLE
inconsistent scaffolds from paf file

### ISSUE THREAD

**Issue by dcopetti** [malonge/RagTag#47]
Hello,
I am using RagTag to anchor contigs (230 Mb plant, HiFi data) based on an assembly of a closely-related species and I see discrepancies between the results of the WGA and the composition of the scaffolds.
The command was 
`ragtag.py scaffold -t 45 -j cp_mt_list -o HalH2_ragtag2 reference.fa assembly.fa`
and here are the alignments before and after the scaffolding (in the former I removed from the paf file the lines for the very small contigs).
[HalH2_RagTag_scaffolds.pdf](https://github.com/malonge/RagTag/files/6056627/HalH2_RagTag_scaffolds.pdf)
Most of the contigs (y axis) map to a single reference chromosome (x), but after `ragtag scaffold` (second image) the new sequences in y align to different chromosomes (x) and also have discordant orientation (see ragtag scaffolds 1,6,7 for example).

I wonder how to explain this shuffling of sequences when the assignments to a reference seem so "obvious" from the raw alignment file.
I ended up making the pseudos myself - did you notice similar behavior in other cases? I can share the alignment file if needed.
Thanks,
Dario

**Comment by malonge** [comment]
Hi there,

Yes this is very strange indeed. I have not quite seen this before - I hope you don't mind helping me debug even though you already made your own pseudomolecules.

Would you be willing to share the assemblies? Or else, it would be helpful to get the `query_against_ref.paf` and the AGP files.

Sometimes, minimap2 is not suitable for certain assemblies, and nucmer works much better. If you have the time, you can try rerunning with `--aligner nucmer --nucmer-params='--maxmatch -l 100 -c 500'` 

Thanks

**Comment by dcopetti** [comment]
I just sent you the files privately.
Spoiler alert: with nucmer the scaffolds look as they should

**Comment by malonge** [comment]
I provided some brief information in #48. Eventually, I will include more information in the docs. Thanks!

**Comment by ASLeonard** [comment]
@malonge, apologies for jumping into a closed issue.

I was wondering if using [unimap](https://github.com/lh3/unimap) instead of minimap2 might similarly be able to resolve this issue. Heng says "[unimap] is recommended over minimap2 for alignment between high-quality assemblies". It also appears to have presets for read-to-assembly mapping, so should also work for the correction module of RagTag.

I haven't had any issues using minimap2 with RagTag, so don't have any meaningful data to test if this issue gets fixed.

**Comment by malonge** [comment]
Hi @ASLeonard,

I had not heard of unimap until now - thanks for bringing it to my attention.

It is fairly easy for me to add this as another option for users (with `--aligner`), though I may leave mm2 as the default.

I am working on v2.0.0 now so I can incorporate this there.

Thanks
