### ISSUE TITLE
Probable typo for scaffold err file

### ISSUE THREAD

**Issue by ASLeonard** [malonge/RagTag#50]
There might be a typo [here](https://github.com/malonge/RagTag/blob/0b18937e9194671d4fd005091f77a616b6bba673/ragtag_scaffold.py#L321), where the log file is `ragtag.scaffold.err`. All the other files are of the form ragtag.scaffold*s*. Only an aesthetic issue, but gets in the way of tab completion.

**Comment by malonge** [comment]
In fact, I have already changed this in the v2 branch:

correct - 01b7bb9388f27fe7d440ca24c4a3257ae5ed919e
scaffold - c0264bb6607322204bcaf4f55a0aaabab397560d
merge - 8511ad8b1be998f71b52e9ec8e77a8ee2378d8c9

**Comment by ASLeonard** [comment]
This is now resolved with the release, but the wiki page for scaffolding still shows `*.scaffolds.*` in the output section, which has now changed.

**Comment by malonge** [comment]
Thanks - yeah I will be updating the docs over the next week. You can tell which have been updated by looking at the version at the top.
