### ISSUE TITLE
Scaffolding proceeds even with empty paf file

### ISSUE THREAD

**Issue by ASLeonard** [malonge/RagTag#51]
Hi,
This is 99% user error, so the observed behaviour may be "working as intended".

When there is an error in the alignment phase, this doesn't seem to get picked up any where during scaffolding and all the output exists (but is identical to the input). In my case, it was because of a permission error on the fasta file, resulting in a size 0 paf.

Skimming the code in _ragtag\_scaffold.py_, would it make sense to add a check around L396 (`ctg_alns = read_genome_alignments(...)`) that there are >0 alignments? Without any alignments here, the output is trivially going to match the input, and so isn't really "scaffolding" anything.

thanks,
Alex

**Comment by malonge** [comment]
Hi there,

Thanks for looking into this. I think this is a reasonable check to add and I will look into adding it in v2.0.0.

Thanks,
Mike
