### ISSUE TITLE
incomplete and incorrect scaffolding

### ISSUE THREAD

**Issue by dcopetti** [malonge/RagTag#53]
Hello,
I am using RagTag to anchor hifiasm contigs to a reference assembly of another genotype in the same plant species. I just wanted to let you know that I get two types of errors in the same chromosome: two RagTag scaffolds do not get merged in a unique sequence (as indicated by the reference assembly), and (coincidentally, in the same chr) one contig is not reverse complemented.
Here is how it looked before (right) and after (left). The numbers are the contg IDs.
<img width="668" alt="chr7_steps" src="https://user-images.githubusercontent.com/13842014/114559125-b0686f00-9c6b-11eb-9236-670c4a00e815.PNG">
The command I run was 
`ragtag.py scaffold -t 40 -o output_ragtag reference.fa contigs.fa`
and it used minimap2 to align.

I was able to fix it by editing the agp file, running `agpcheck` and `agp2fasta` and it all looked fine afterwards.
This is just a FYI, if you want to troubleshoot I can share the files
Cheers,

Dario

**Comment by malonge** [comment]
Hi Dario,

Thanks for bringing this to my attention. I am glad the other utilities helped you out. I would very much like to take a look at this if you share the data with me at malonge11@gmail.com. I will keep everything private and delete the data when I am done.

Thanks,
Mike

**Comment by malonge** [comment]
Hi Dario,

After looking at your data, it appears that the assemblies are structurally divergent which is making scaffolding difficult. There are many hifiasm contigs that align quite well to multiple reference sequences, for example (like `ptg000004l`). If you expect these to be misassemblies, you can use `ragtag.py correct`. If you think they are genuine structural differences, you may consider scaffolding with multiple reference genomes with `ragtag.py merge` or using another map for scaffolding.

**Comment by dcopetti** [comment]
Hi Mike,

You are right: I should have mentioned that Alyrata is the reference (the 8 longest sequences named “scaffold” are the 8 chrs), LyrH2 is the query, the assembly I want to scaffold.
Yes of course, here attached is the agp before and after (_DC) the edit. The edit involved the three contigs that then ended up on chr7


I attach also an alignment of the scaffolds to the reference before RagTag, and the only big “misassembly” I saw is the one at ptg4 that you point out too. I did extensive investigation on whether it was indeed a misassembly and could not confirm that it was. At the junctions of the regions there are two different tandem repeat arrays (hint towards a possible misassembly?) but the HiFi reads align homogeneously there (no clear evidence, so I trust the assembler). On the other hand, I aligned genetic markers (unfortunately just a handful per chr) of an individual of the same species to the contigs and none of the ones on LG1 was aligning to the portion on ptg 4. So no clear evidence on that side too.
The reference we have here is 10 years old (https://www.nature.com/articles/ng.807) and the large-scale scaffolding is not so reliable to me. So for now we decided to keep the assembly as it is for... lack of evidence supporting the misassembly.
Hoping this helps,

Dario

Molecular Plant Breeding
Institute of Agricultural Sciences
ETH Zurich - LFW A53<http://www.mapsearch.ethz.ch/map/mapSearchPre.do?gebaeudeMap=LFW&lang=en>
Universitaetstrasse 2<https://maps.google.com/?q=Universitaetstrasse+2&entry=gmail&source=g>
8092 Zurich, Switzerland
www.mpb.ethz.ch<http://www.mpb.ethz.ch/>

**Comment by dcopetti** [comment]
Sure, I shared the files with you.

I sent you also an alignment of the scaffolds to the reference before RagTag, and the only big “misassembly” I saw is the one at ptg4 that you point out too. I did extensive investigation on whether it was indeed a misassembly and could not confirm that it was. At the junctions of the regions there are two different tandem repeat arrays (hint towards a possible misassembly?) but the HiFi reads align homogeneously there (no clear evidence, so I trust the assembler). On the other hand, I aligned genetic markers (unfortunately just a handful per chr) of an individual of the same species to the contigs and none of the ones on LG1 was aligning to the portion on ptg 4. So no clear evidence on that side too.
The reference we have here is 10 years old (https://www.nature.com/articles/ng.807) and the large-scale scaffolding is not so reliable to me. So for now we decided to keep the assembly as it is for... lack of evidence supporting the misassembly.

**Comment by malonge** [comment]
Hi Dario,

I spotted quite a few contigs with large structural differences. Here is a list of a few that I found:

```
ptg000017l
ptg000010l
ptg000023l
ptg000034l
ptg000007l
```

I also calculated the average alignment identity to be somewhere around 90-93%. If I had no other info, I would guess that these two samples are not from the same species.

**Comment by dcopetti** [comment]
Hi Mike,

Thank you for reporting those cases.
I saw them too, and checked the contigs by looking at the realignment of the reads. The inconsistencies with the reference are well supported by reads, and many regions are just parts that were not assembled before. Also, that assembly was made with Sanger sequencing from plasmid, fosmid, and BAC data, anchored with low resolution genetic maps (~30 markers per LG) of other genotypes. Also the low sequence similarity is expected in this case, being a plant sample from different populations.
For the reasons above, we decided to trust our assemblies and proceed with the contigs as they are – could be real biological variation or misassemblies in the old reference.

Cheers,
Dario



Molecular Plant Breeding
Institute of Agricultural Sciences
ETH Zurich - LFW A53<http://www.mapsearch.ethz.ch/map/mapSearchPre.do?gebaeudeMap=LFW&lang=en>
Universitaetstrasse 2<https://maps.google.com/?q=Universitaetstrasse+2&entry=gmail&source=g>
8092 Zurich, Switzerland
www.mpb.ethz.ch<http://www.mpb.ethz.ch/>

**Comment by malonge** [comment]
Thanks Dario,

Yeah it sounds reasonable to trust the hifiasm contigs. It can be tough to discern scaffolding accuracy when using such a reference, but it sounds like you are taking a reasonable approach. It is reassuring to know that you employed some of the other utilities to clean things up, since that is exactly their purpose.

**Comment by dcopetti** [comment]
Good to hear that!
The function from agp to scaffolds is definitely useful - I think I will need it again in the future.

Could you figure out what the issue was with this incomplete scaffolding? Is it something we should expect to happen? was there any culprit of what triggered it?
Of course, it is always recommendable to inspect the results of a software.
Thank you for the prompt and effective support!
