### ISSUE TITLE
which scaffolds make up one chromosome

### ISSUE THREAD

**Issue by jinshangkun** [malonge/RagTag#54]
Hello! Thanks for your application firstly. I want to know which scaffolds make up one chromosome, but no result file contains this information. Can ragtag output this file ?

**Comment by malonge** [comment]
Hi there,

The scaffolding results are stored in the AGP files. For scaffolding, that should be `ragtag.scaffolds.agp`.

Let me know if this answers your question.

Thanks

**Comment by jinshangkun** [comment]
Thanks! I got it.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "malonge/RagTag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月29日(星期四) 晚上9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [malonge/RagTag] which scaffolds make up one chromosome (#54)





 
Hi there,
 
The scaffolding results are stored in the AGP files. For scaffolding, that should be ragtag.scaffolds.agp.
 
Let me know if this answers your question.
 
Thanks
