### ISSUE TITLE
Are "N" in reference able to be preserved  in scaffolding?

### ISSUE THREAD

**Issue by jo-mc** [malonge/RagTag#57]
Just started looking at ragtag. When I correct and scaffold to a reference, it would appear that the reference N's are not in the scaffolds. Is there a way to include those?  I want to compare regions of the scaffold to regions of the reference. Thanks.

Looking some more I assume the data I am after is in the agp file (have not seen these before)  will look into this.

**Comment by malonge** [comment]
Hi there,

Sequence is never added or subtracted in `correct` or `scaffold`, so if this is observed, then it would be considered a bug. I wonder if the gaps got cut into their own contigs during correction, and then these contigs were left unplaced during scaffolding. As you say, you can check this in the AGP files, which gives all the information about how sequence was arranged.

Thanks,
Mike
