### ISSUE TITLE
Error given in scaffold.py line 533 and 539 

### ISSUE THREAD

**Issue by Darcy220606** [malonge/RagTag#58]
Hi there,

Thanks a lot for this very user friendly tool. 

Im trying to run the Ragtag scaffolding on a fasta file with assembled contigs using a full plasmid sequence as the reference. However, it seems that i keep running into this error when trying to generate the stats, (I attached a screenshot)  
<img width="582" alt="Screenshot 2021-05-12 183958" src="https://user-images.githubusercontent.com/81744003/118012856-c98b3b00-b351-11eb-9036-cd07ea62ce7b.png">
Any idea what the problem may be in? Suggestions are much welcomed.

Thank you

**Comment by malonge** [comment]
Hi there,

Thank you for bringing this to my attention. Could you share the contents of `ragtag_output/ragtag.scaffold.err`?

Thanks,
Mike

**Comment by Darcy220606** [comment]
Hey Mike,

Indeed, i attached it here; 
<img width="357" alt="Screenshot 2021-05-12 182850" src="https://user-images.githubusercontent.com/81744003/118013938-f4c25a00-b352-11eb-8083-492416586990.png">

**Comment by malonge** [comment]
Hi there,

So it looks as if there is something wrong with the `ragtag.scaffold.confidence.txt` file. Can you let me know what is in that file? And could you also share the original command that you used?

Thanks,
Mike

**Comment by Darcy220606** [comment]
Hey Mike, 

So the ragtag.scaffold.confidence.txt has the headings and nothing else unfortunately. 
Sure - so i used:

ragtag.py scaffold \
~/05_ragtag_results/correcting/pM/*.corrected.fasta ~/Input/First_batch_ref_seq/pM/pM.fasta \
-u \
-t 20 \
-o ~/05_ragtag_results/scaffolding/pM

Thanks.

**Comment by malonge** [comment]
hmm I wonder if the problem is that every contig was left unplaced. If so, I would consider this a bug, because the software should be able to handle this. That said, this would usually indicate a problem if no contigs were scaffolded. 

Can you describe the two assemblies being used here? Perhaps `~/05_ragtag_results/correcting/pM/*.corrected.fasta` should actually be the query assembly?

**Comment by Darcy220606** [comment]
Sure thing, so the corrected.fasta is the corrected contig assembly made by Spades and then corrected by Ragtag (there are around 10,000 contigs).  The reference sequence is one 7,000 bp plasmid sequence and thats the pM.fasta. I changed the order in the command and ran it again but it still keeps giving me the same error.

**Comment by malonge** [comment]
Hi there,

Since you are changing the input, you will need to run with `-w`. Or else you can delete the output directory and start from scratch. Otherwise, ragtag will use the same alignment files.

**Comment by Darcy220606** [comment]
Hi There,

The issue is now resolved. 

Thanks again for a very handy tool.
