### ISSUE TITLE
Default behaviour for specifying threads and mm_params isn't clear

### ISSUE THREAD

**Issue by ASLeonard** [malonge/RagTag#59]
Luckily asm-ref mapping is pretty quick anyway, so I never noticed this before, but explicitly specifying threads for mapping and custom mapping parameters leads to the thread parameter not being used. There is a line in the scaffolding file which appends the user set `-t` only if the params are the default. 

It's easy to fix by specifying `-t` inside the mm_params, but this isn't obvious from the documentation, which just states that the ragtag param `-t` sets this value.

**Comment by malonge** [comment]
Hi there,

Yeah I agree that this is unclear. I will update the usage message and that will eventually be released in the next version update.
