### ISSUE TITLE
is RagTag deterministic?

### ISSUE THREAD

**Issue by ricardo-aaron** [malonge/RagTag#64]
I run ragtag.py scaffold one time and get 774 unplaced contigs. I run it a second time, same everything, and get 805 unplaced contigs. I like the 774 version better. Why would I get two different scaffoldings using the same input files?

**Comment by malonge** [comment]
Hi there,

It should be deterministic, at least in the latest version. Could you provide the exact command you used and the version number?

**Comment by ricardo-aaron** [comment]
The exact command line for the first run I didn't write it down (first time use, saw that it worked and went on; thought ragtag would create a log file with the command line; maybe you could add that?), but the minimap2 command from the paf.log file is 'minimap2 -x asm5 -t 24 ref.fa contigs.fasta', so I'm 95% confident the command line was 'ragtag.py scaffold -t 24 ref.fa contigs.fasta', with RagTag conda v1.1.1 and minimap2 2.17. The second run was 'ragtag.py scaffold -u -t 12 -o outdir ref.fa contigs.fasta' with RagTag conda v2.0.1 and minimap2 2.17. I uninstalled and re-instaled conda version 1.1.1 and now I get 806 unplaced contigs. I haven't been able to re-create the 774 unplaced version (and I don't think I ever will... sad...). There are differences between run 1 v1.1.1 (774 unplaced) and run 2 v1.1.1 run (806 unplaced) across all final chromosomes. The difference between the v2.0.1 run (805 unplaced) and v1.1.1 run 2 (806 unplaced) is in one chromosome.
Running v2.0.1 a second time does indeed return the exact same assembly.

**Comment by malonge** [comment]
Hi there,

Thanks for checking that. While RagTag should be deterministic for those versions, it will also use any preexisting alignment files. So sometimes the results can look different if RagTag finds an older alignment file. You can delete the intermediate output or run with `-u` to ensure that everything is consistent.

It sounds like you are interested in exploring different results for your assembly, so I suggest trying out different aligners or parameters. I definitely recommend running with nucmer, if you can spare the time. But I recommend specifying a new output directory with `-o` to keep the results separate. I also recommend sticking with v2.0.1 from here on out.

Thanks
