### ISSUE TITLE
Ragtag vs Ragoo

### ISSUE THREAD

**Issue by angusdavison** [malonge/RagTag#65]
Hi there, I aim to assemble a genome based on Illumina reads, using a closely related reference genome. Ragoo seems ideal but is no longer supported, yet I can't see the same functionality in Ragtag. Is this because I am being dim, or it has this function not yet been included Ragtag? If the latter, then I will go ahead and use Ragoo. Thanks

**Comment by malonge** [comment]
Hi there,

Both RaGOO and RagTag only scaffold assemblies based on pairwise whole-genome alignment. Neither tool will assemble reads. Please let me know if I am misunderstanding your question.

In case it is helpful, RagTag ['scaffold'](https://github.com/malonge/RagTag/wiki/scaffold) and ['correct'](https://github.com/malonge/RagTag/wiki/correct) are the updated features from RaGOO.

Thanks

**Comment by angusdavison** [comment]
Hi, thanks for your quick response. I misunderstood the use of the software. Apologies!
