### ISSUE TITLE
RagTag correct is slow in mammalian genome

### ISSUE THREAD

**Issue by yuzhenpeng** [malonge/RagTag#69]
Hi, I try to use RagTag correct for mammalian genome. But it runs very slow. 
Could you please give me some help.

`ragtag.py correct westar.fasta ZYCR1-genome.clean.fa -t 30`

Thank you.

Zhenpeng

**Comment by malonge** [comment]
Hi there,

Is the limiting step the minimap2 alignment step? Unfortunately, RagTag's speed is usually dependent on alignment speed, which can be variable depending on your samples. But please let me know if there are RagTag-specific portions that are taking too long, either before or after alignment. You can check this by looking at the stderr.

Thanks
