### ISSUE TITLE
How to understand two modles (fill-only and join-only) of patch?

### ISSUE THREAD

**Issue by CAShuangchao** [malonge/RagTag#75]
Hi, malonge:
I was very surprised by the update of Ragtag after it was added to **patch**, but I still couldn't understand the difference between fill-only and join-only.
The problem I have is that when I get two assemblies using different software, such as Hifiasm and Hicanu, and anchor them to chromosomes using **Ragtag Scaffod**, I find that they can use each other's assemblies to fill their own gaps (albeit only partially), as shown in the diagram. It seems to me that ragtag patch is competent for this operation. Although I have carefully read their description in the wiki, I still don't understand the difference between fill-only and join-only, and which one should I choose to complete the operation in the schematic.
I'm still testing with data to try to figure out the difference, and I hope you can help me explain it more clearly.

![image](https://user-images.githubusercontent.com/76389169/129310636-7f2639ef-333b-4d2d-a90e-7e7f3fe82f96.png)

thank you
Huangchao

**Comment by malonge** [comment]
Hi there, 

This seems like a good application for RagTag patch.

`--fill-only` will only fill existing gaps, just like traditional gap-filling tools. 

`--join-only` will not fill existing gaps, but it will try to order and orient distinct sequences, and then fill the gap between them.

By default, RagTag patch will do both. If you have already scaffolded both assemblies, and you no longer want any more scaffolding, then `--fill-only` is a reasonable option. Please reopen the issue if things are still not clear.

Thanks,
Mike

**Comment by CAShuangchao** [comment]
Hi, 
Tested separately with my data, I understand it. **Patch** helps me achieve this goal well. The newly added **patch** and **merge** make **RagTag** more powerful in reference-based assembly, I estimate it will definitely be favored by more people in the future.

Thanks
HuangChao

**Comment by malonge** [comment]
thank you!
