### ISSUE TITLE
RagTag : command for patching

### ISSUE THREAD

**Issue by anita-icgeb** [malonge/RagTag#77]
I am struggling understanding the target.fa and query.fa files. By default does it fill gaps and joins scaffolds in case if we don't invoke --fill-only or --join-only ? The output of patching gives two fasta files (ragtag.patch.ctg.fasta and ragtag.patch.rename.fasta), so what is the use of ragtag.patch.ctg.fasta and how to proceed further after getting these fasta files?

**Comment by malonge** [comment]
Hi there,

This should answer your question: https://github.com/malonge/RagTag/wiki/patch
