### ISSUE TITLE
Whether ragtag could conduct the unique match on the reference genome 

### ISSUE THREAD

**Issue by jinxin112233** [malonge/RagTag#78]
Hi

There are multiple contigs at the same position in the  ref genome that form a match, and we want to ask whether ragtag have  parameters that can get a unique match. 

Best wish
Jinxin

**Comment by malonge** [comment]
Typically `-f`, `--remove--small`, and `-q` are the parameters for this. The Wiki can provide more details:

https://github.com/malonge/RagTag/wiki/Glossary#unique
