### ISSUE TITLE
hic.bam

### ISSUE THREAD

**Issue by Kai-Maker1** [malonge/RagTag#79]
Hello malonge,
        Thanks for offering such a good helper.
         As for my question,I want to user hic data to help me resolve conflicts.
         (`ragtag.py merge -b hic.bam query.fasta out_*/*.agp other.map.agp`)
         But how can I produce such a hic.bam file ,can you give me some advice for choosing software application?
 Many thanks in advance.

**Comment by malonge** [comment]
Hi there,

So you'll want to align your Hi-C reads to `query.fasta`. There are many different ways to do this. For a long time, I've used the Arima pipeline:

https://github.com/ArimaGenomics/mapping_pipeline 

Lately, I have started using chromap:

https://github.com/haowenz/chromap

Thanks,
Mike
