### ISSUE TITLE
chromosome alignment stats?

### ISSUE THREAD

**Issue by jantonid** [malonge/RagTag#8]
Hello,
Is there a way to see statistics about the scaffolds of my species' draft assembly mapping to the reference assembly?  For example, can we see somewhere in the output what the number of scaffolds and total length in bp mapped to each of the reference chromosomes (and the unplaced scaffolds in chromosome 0)?
I ask because I'm trying to determine which reference assembly I should use to give me the best pseudochromosome-level assembly from my species' draft scaffold assembly.  I am debating between about 4 potential reference genomes and would like some metrics to compare.  
A chromosome assembly of my species (which is tetraploid and probably quite repetitive) would be expected to be 14 chromosomes and around 1,500Mbp in length.  
I have one reference genome of a more closely-related species (in the same same Order) but it is 16 chromosomes and 400Mbp in length.
I have two other reference genomes of less closely related species that either have the 13 or 15 chromosomes but are also smaller in length.
I have another reference genome even less closely related with 14 chromosomes but much larger in length.
So I'm wondering how I can see the statistics mentioned above in order to make the best choice for a reference genome?
On a similar vein, I am also tweaking parameters to try to improve the pseudochromosome assembly.  I saw that the parameters for minimap can be changed based on sequence divergence, so I've been using "-x asm20" to be on the safe side.  I've also decreased the scaffold length -f to 500bp.  Other than that and the choice of reference genome, do you have an inkling of what other parameters would produce the most realistic pseudochromosome-level assembly for my purposes?
Thank you for any insight you can offer!
--Jenny

**Comment by malonge** [comment]
Hi Jenny,

`ragtag.scaffolds.stats` gives you some basic information. Here is an example from my test data:

```
placed_sequences  placed_bp  unplaced_sequences  unplaced_bp  gap_bp  gap_sequences
1724              812068837  7794                125797960    171100  1711
```

Beyond that, perhaps running [Quast](https://github.com/ablab/quast) on your scaffolds will help you decide.

I recommend running ragtag using all 4 references and saving the AGP files for each. I can't guarantee when I will be able to look at this, but I do plan to build a tool that combines information from multiple AGP files to help improve scaffolding. In the meantime, you can manually compare the AGP files yourself to check what the consistencies/differences are between the different reference sequences. 

As for parameter optimization, I think it is usually a trade-off between localizing more sequences and creating fewer scaffolding errors. What are the assembly stats for your query assembly and how what data did you use to produce it? 

You may also consider running the [correction module](https://github.com/malonge/RagTag/wiki/Correction) to break your contigs prior to scaffolding. 

Thanks

**Comment by jantonid** [comment]
Hi Michael,
Thank you for your reply!

For this particular purpose, the draft assembly I am using is here (length of assembly : ~1100Mbp)
https://www.ncbi.nlm.nih.gov/assembly/GCA_010015005.1#/st
and the reference assembly I've used so far (the closest relative available, but with two more chromosomes and a smaller genome size of ~350Mbp) is here:
https://www.ncbi.nlm.nih.gov/genome/86952

The expected genome size of my species based on c-value is ~1500Mbp.

The results show:
placed_sequences placed_bp unplaced_sequences unplaced_bp gap_bp gap_sequences
3765 272108287 729655 840334616 157165339 733403
It would be great to know which of the chromosomes, including chromosome0, these scaffolds are placed on, to evaluate if it looks realistic/usable/accurate.  I will also be running quast, but it can't give that information.

I did run the correction before the scaffolding. Here were my commands (using educated guesses for how to set the parameters):

ragtag.py correct -u -f 500 -t 30 \
--mm2-params '-x asm20' \
--gff /scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/GCA_010015005.1_ASM1001500v1_genomic.gff3 \
/scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/GCA_012066045.1_ASM1206604v1_genomic.fna \
/scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/GCA_010015005.1_ASM1001500v1_genomic.fa \
&> ragtag.correct.mm2.500.keep.logfile

ragtag.py scaffold -u -f 500 -q 5 -t 30 -C -r \
--mm2-params '-x asm20' \
/scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/GCA_012066045.1_ASM1206604v1_genomic.fna \
/scratch/brown/jantonid/Elm_assembly_transfer/Elm_assemblies_new/GAM-NGS/ragtag_new/ragtag_output_mum1000/ragtag_output_correct/GCA_010015005.1_ASM1001500v1_genomic.corrected.fasta \
&> ragtag.scaffold.mm2.500.keep.logfile

Thanks again for any insight!
--Jenny


________________________________

**Comment by malonge** [comment]
Hi there,

All the contig placement information is available in the AGP files. That should tell you where everything was put.

I guess I am a little confused; it looks like your query assembly is over 3X the size of the reference. Is that correct? That is not necessarily a deal-breaker, but it would mean that the results should be carefully scrutinized.

Thanks

**Comment by jantonid** [comment]
Hi Michael,
In case this didn't go through on email yesterday...

Yes, the initial reference used is much smaller in size, but it was the closest relative (same Order) available with a chromosome assembly.

Some other references I'm considering are:
I have two other reference genomes of less closely related species that either have the 13 or 15 chromosomes but are also smaller in length than my species.
I have another reference genome even less closely related with 14 chromosomes (the same # as my species) but much larger in length.

I have two AGP files from the run with the initial reference (attached in email).  I would look at the scaffolding AGP to try to determine if placement looks good, correct?  And it looks like for updategff I would use the AGP file from the correction step?  (I think my initial gff file I gave for the correction step was incorrect, so I'm trying to find an accurate gff and redo the ragtag steps, but I don't think that affects the other output mentioned.)

Thanks again!
Jenny

**Comment by malonge** [comment]
Hi there,

Yes, all of that sounds good. Sorry about the lack of documentation - I am actively working on it. But for the update gff, you wanted to use the AGP associated with the appropriate step. So usually it goes something like this.

1. `ragtag.py correct` using `--gff`. Produces `ragtag.correction.agp`
2. update the gff using `ragtag.correction.agp`. call that gff_2
3. `ragtag.py scaffold`. Produces `ragtag.scaffolds.agp`
4. update gff_2 using `ragtag.scaffolds.agp`

I will close the issue for now, but generally, I will say that since you are still working with relatively distantly related species, I recommend trying out a bunch of different things, comparing/contrasting, and hopefully validating with some independent data. 

Thanks
