### ISSUE TITLE
Inputing the paired-end reads to correct module

### ISSUE THREAD

**Issue by yasinkaymaz** [malonge/RagTag#80]
Hi, 

First of all thanks for this amazing tool. I was wondering whether you could update your tutorial page about how to input especially paired-end reads. -R and -F seem to be doing the job but a slightly detailed demo would help tremendously. I figured a way by writing the read full paths to an input text file (with -F) but curious whether that's the way it should be.

Best,

**Comment by malonge** [comment]
Hi there,

RagTag does not support the use of paired-end alignment info for validating corrections. You can just treat the paired-end reads as single-end reads.

Thanks
