### ISSUE TITLE
Error when running ragtag patch command

### ISSUE THREAD

**Issue by kayobianco** [malonge/RagTag#81]
Hi! 
When running ragtag patch, I received the following error:

(base) kayobianco@MacKayo ~ % ragtag.py \                             
patch \
/Users/kayobianco/Downloads/NZ_CP021520.fasta \
/Users/kayobianco/ragtag_output/ragtag.correct.fasta
Sat Sep 18 11:19:55 2021 --- VERSION: RagTag v2.0.1
Sat Sep 18 11:19:55 2021 --- WARNING: This is a beta version of `ragtag patch`
Sat Sep 18 11:19:55 2021 --- CMD: ragtag.py patch /Users/kayobianco/Downloads/NZ_CP021520.fasta /Users/kayobianco/ragtag_output/ragtag.correct.fasta
Sat Sep 18 11:19:55 2021 --- WARNING: Without '-u' invoked, some component/object AGP pairs might share the same ID. Some external programs/databases don't like this. To ensure valid AGP format, use '-u'.
Sat Sep 18 11:19:55 2021 --- INFO: Retaining pre-existing file: /Users/kayobianco/ragtag_output/ragtag.patch.ctg.fasta
Sat Sep 18 11:19:55 2021 --- INFO: Retaining pre-existing file: /Users/kayobianco/ragtag_output/ragtag.patch.rename.fasta
Sat Sep 18 11:19:55 2021 --- INFO: Retaining pre-existing file: /Users/kayobianco/ragtag_output/ragtag.patch.comps.fasta
Sat Sep 18 11:19:55 2021 --- INFO: Mapping the query genome to the target genome
Sat Sep 18 11:19:55 2021 --- INFO: Running: nucmer --maxmatch -l 100 -c 500 -p /Users/kayobianco/ragtag_output/ragtag.patch.asm /Users/kayobianco/ragtag_output/ragtag.patch.ctg.fasta /Users/kayobianco/ragtag_output/ragtag.patch.rename.fasta 2> /Users/kayobianco/ragtag_output/ragtag.patch.asm.delta.log
Traceback (most recent call last):
  File "/Users/kayobianco/miniconda3/bin/ragtag_patch.py", line 518, in <module>
    main()
  File "/Users/kayobianco/miniconda3/bin/ragtag_patch.py", line 372, in main
    al.run_aligner()
  File "/Users/kayobianco/miniconda3/lib/python3.7/site-packages/ragtag_utilities/Aligner.py", line 172, in run_aligner
    run_e(self.compile_command(), self.out_log)
  File "/Users/kayobianco/miniconda3/lib/python3.7/site-packages/ragtag_utilities/utilities.py", line 107, in run_e
    if subprocess.call(cmd, stderr=f_err) != 0:
  File "/Users/kayobianco/miniconda3/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/kayobianco/miniconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Users/kayobianco/miniconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nucmer': 'nucmer'

Can you help me?

**Comment by malonge** [comment]
To solve this issue, just install Nucmer. If its not in your PATH, you can point to the executable with `--aligner`. 

https://github.com/malonge/RagTag/wiki/Installation
