### ISSUE TITLE
Correct Error -- stats: invalid option -- '@'

### ISSUE THREAD

**Issue by dirkjoldersma** [malonge/RagTag#87]
I ran into an error at the end of correct program. (I ran the program again on the same subdirectory, so you can see the progress to error below.) Program stopped after error, however it added no content to correct.ragtag.err.  sam and bam files seem fine in terms of size relative to reads and to each other. 

(base) jovyan@a6e329793:~/work$ ragtag.py correct Fragaria_vesca4.0.a1.fasta YW_de_novo_nanopore_high_resampling.fasta -R nanopore_reads.fastq.gz -o ragtag_correct_H4 -T ont
Wed Nov  3 20:48:17 2021 --- VERSION: RagTag v2.1.0
Wed Nov  3 20:48:17 2021 --- CMD: ragtag.py correct Fragaria_vesca4.0.a1.fasta YW_de_novo_nanopore_high_resampling.fasta -R nanopore_reads.fastq.gz -o ragtag_correct_H4 -T ont
Wed Nov  3 20:48:17 2021 --- WARNING: Without '-u' invoked, some component/object AGP pairs might share the same ID. Some external programs/databases don't like this. To ensure valid AGP format, use '-u'.
Wed Nov  3 20:48:17 2021 --- INFO: Mapping the query genome to the reference genome
Wed Nov  3 20:48:17 2021 --- INFO: Retaining pre-existing file: /home/jovyan/work/ragtag_correct_H4/ragtag.correct.asm.paf
Wed Nov  3 20:48:17 2021 --- INFO: Reading whole genome alignments
Wed Nov  3 20:48:17 2021 --- INFO: Filtering and merging alignments
Wed Nov  3 20:48:17 2021 --- INFO: Validating putative query breakpoints via read alignment
Wed Nov  3 20:48:17 2021 --- INFO: Aligning reads to query sequences
Wed Nov  3 20:48:17 2021 --- INFO: Retaining pre-existing read alignments: /home/jovyan/work/ragtag_correct_H4/ragtag.correct.reads.s.bam
Wed Nov  3 20:48:17 2021 --- INFO: Compressing, sorting, and indexing read alignments
Wed Nov  3 20:48:17 2021 --- INFO: Retaining pre-existing file: /home/jovyan/work/ragtag_correct_H4/ragtag.correct.reads.s.bam
Wed Nov  3 20:48:17 2021 --- INFO: Indexing read alignments
Wed Nov  3 20:48:17 2021 --- INFO: Retaining pre-existing file: /home/jovyan/work/ragtag_correct_H4/ragtag.correct.reads.s.bam.bai
Wed Nov  3 20:48:17 2021 --- INFO: Validating putative query breakpoints
Wed Nov  3 20:48:17 2021 --- INFO: Calculating global read coverage
stats: invalid option -- '@'

**Comment by malonge** [comment]
Hi there, what samtools version are you using?

**Comment by dirkjoldersma** [comment]
Hi, thanks for your response .... 

(base) jovyan@a6e329793:~/work$ samtools --version
samtools 1.3.1
Using htslib 1.3.1
Copyright (C) 2016 Genome Research Ltd.

I tried to upgrade with conda and it appears to be latest available.

**Comment by dirkjoldersma** [comment]
Just noodling around in samtools in my environment, I can directly run samtools view with -@ option. I can also run mpileup, so long as I skip a threads or -@ option. 

However, I can NOT run samtools depth or samtools mpileup with options like -@ or -t or --threads . 

Is there a way that I can just run the programs manually and provide the input to ragtag? What file post-script will ragtag look for after this process?

**Comment by malonge** [comment]
Sorry, I just remembered thatI really should have asked about your pysam version. Anyways, specific version numbers used to develop and test RagTag can be found in the [wiki](https://github.com/malonge/RagTag/wiki/Installation). You can always make a conda environment using those specific version numbers.

If you'd like to try to make the files independently, here's the relevant code. Hopefully you can tell from that what the samtools command would be and what the name of the output file should be:

#### compress
```
pysam.view("-@", str(num_threads), "-b", "-o", output_path + "ragtag.correct.reads.bam", output_path + "ragtag.correct.reads.sam", catch_stdout=False)
```

#### sort
```
pysam.sort("-@", str(num_threads), "-o", output_path + "ragtag.correct.reads.s.bam", output_path + "ragtag.correct.reads.bam", catch_stdout=False)
```

#### index
```
pysam.index(output_path + "ragtag.correct.reads.s.bam", catch_stdout=False)
```

#### stats
```
pysam.stats("-@", str(num_threads), output_path + "ragtag.correct.reads.s.bam")
```

**Comment by dirkjoldersma** [comment]
Hey -- thanks for advice ... I got it to work. I ran samtools stats ragtag.correct.reads.s.bam > ragtag.correct.reads.s.bam.stats in the output directory, then ran the initial ragtag.py correct command and it successfully finished, at least on an ecoli genome. On to plants, but this should work. Thanks again.
