### ISSUE TITLE
RagTag error: "OSError: error when opening file"

### ISSUE THREAD

**Issue by zhousun21** [malonge/RagTag#90]
I am running RagTag to scaffold an assembly.

It runs fine, makes the log file and part of the output, but at the last step gives an error:

OSError: error when opening file

Along with the path for the file it is trying to open (target.fasta) . The path is correct, the file exists, there are no permission errors. The rets of the program runs correctly but it won't output the scaffolds.

Does anyone have any idea what could be wrong?

The command I am using is:
ragtag.py scaffold -u -w --mm2-params '-x asm20' reference.fasta target.fasta &

I have also tried running without any of the parameters and it gives the same error.

**Comment by malonge** [comment]
Please provide the output logs.

**Comment by zhousun21** [comment]
Here is the ouput log.  Note that the error isn't in it, it only appeared on the screen:
__________________________
[M::mm_idx_gen::26.078*1.54] collected minimizers
[M::mm_idx_gen::31.956*1.80] sorted minimizers
[M::main::31.956*1.80] loaded/built the index for 1301551 target sequence(s)
[M::mm_mapopt_update::33.599*1.76] mid_occ = 465
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 0; #seq: 1301551
[M::mm_idx_stat::34.284*1.75] distinct minimizers: 97666976 (80.89% are singletons); average occurrences: 2.370; average spacing: 5.623
[M::worker_pipeline::87.886*2.51] mapped 135187 sequences
[M::worker_pipeline::96.183*2.48] mapped 232103 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x asm20 /home/zhousun/ery_coc_asm_2/reference.fasta /home/zhousun/ery_coc_asm_2/target.fasta
[M::main] Real time: 96.238 sec; CPU: 238.206 sec; Peak RSS: 10.364 GB

**Comment by zhousun21** [comment]
Is there a commandline parameter I can use to allow Ragtag to access more memory?  I'm not sure that's the issue but I'd like to try it if possible.

**Comment by malonge** [comment]
Sorry I meant please share what was printed stderr (the screen, in your case). The above log is another log file for jobs executed from within RagTag

**Comment by zhousun21** [comment]
OK, thanks for clarifying.  I'm running this again to regenerate the error message.  I'll post it here shortly.

**Comment by zhousun21** [comment]
This was the on-screen error:
______________________________
[E::fai_build_core] Different line length in sequence '834'
Traceback (most recent call last):
  File "/usr/local/RagTag/2.0.1/bin/ragtag_scaffold.py", line 4, in <module>
    __import__('pkg_resources').run_script('RagTag==2.0.1', 'ragtag_scaffold.py')
  File "/usr/local/RagTag/2.0.1/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/RagTag/2.0.1/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/RagTag/2.0.1/venv/lib/python3.8/site-packages/RagTag-2.0.1-py3.8.egg/EGG-INFO/scripts/ragtag_scaffold.py", line 577, in <module>
  File "/usr/local/RagTag/2.0.1/venv/lib/python3.8/site-packages/RagTag-2.0.1-py3.8.egg/EGG-INFO/scripts/ragtag_scaffold.py", line 555, in main
  File "/usr/local/RagTag/2.0.1/venv/lib/python3.8/site-packages/RagTag-2.0.1-py3.8.egg/EGG-INFO/scripts/ragtag_scaffold.py", line 136, in write_orderings
  File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 183, in pysam.libcfaidx.FastaFile._open
OSError: error when opening file `/home/zhousun/ery_coc_asm/target.fasta`

**Comment by zhousun21** [comment]
I'm noticing something now, the first line:
__________________________________
[E::fai_build_core] Different line length in sequence '834'
__________________________________
The sequence in question has a first line shorter than the others are the result of a previous contaminant removal.   It didn't occur to me that would be a problem, but maybe it is.  I just reformatted it to have a fastawrap=70 to see if that helps.

**Comment by malonge** [comment]
Thanks, let me know if that works. It looks like pysam raised the error, so you might even try using `samtools faidx` as a quick check to make sure your FASTA file is properly formatted.

**Comment by zhousun21** [comment]
Yes, that solved the problem!
A fasta file with unequal length lines returned a "file can't be opened" error.   :)
