### ISSUE TITLE
Why not use Nucmer 4?

### ISSUE THREAD

**Issue by Yutang-ETH** [malonge/RagTag#93]
Hi Malonge,

Happy new year. I just installed RagTag via conda and I found the version of installed Nucmer is 3 not 4. Version 4 provides multi-thread mode, would you consider version 4 in future release? Or is there a specific reason that you use version 3?

Best wishes,
Yutang

**Comment by malonge** [comment]
Hi Yutang,

I haven't tried this before, but I think it should work if you just install Nucmer 4 yourself and then point to the executable with `--aligner`. And then you can pass whatever parameters you want (except for `-p`) via `--nucmer-params`.

Let me know if that works.

**Comment by Yutang-ETH** [comment]
Hi Malonge,

Thank you very much for your reply. Yes, exactly, that's what I would like to try. I will try minimap2 first and then try Nucmer 4 later. If I make any progress, I will let you know here.

Best wishes,
Yutang

**Comment by Yutang-ETH** [comment]
Hi Malonge,

Just to let you know, I installed mummer 4 in the ragtag conda environment and then added --nucmer-params '--maxmatch -t 30 -l 100 -c 500', it worked.

Thank you very much,
Yutang

**Comment by Yutang-ETH** [comment]
Hi Malonge,

Just to let you know, when I removed --maxmatch from --nucmer-params, it didn't work anymore.

(ragtag) bash-4.2$ ./RAGTAG_h2.sh
usage: ragtag.py patch <target.fa> <query.fa>
ragtag_patch.py: error: argument --nucmer-params: expected one argument

Here's my command line:
ragtag.py patch target.fa query.fa -o ragtag_flye_h2_miop10 -u --aligner nucmer --nucmer-params '-t 30 -l 100 -c 500'

What could be wrong?

Best wishes,
Yutang

**Comment by malonge** [comment]
Do you get the same error using Nucmer 3? If so, please open up a separate issue.

**Comment by Yutang-ETH** [comment]
Thank you very much for your reply. No problem for Nucmer 3.

**Comment by malonge** [comment]
idk iit seems like a problem with the argument parsing Maybe try `--nucmer-params="-t 30 -l 100 -c 500"`. Or variations on that.

**Comment by pailloufat-stack** [comment]
Hello, @Yutang-ETH  @malonge , I am also interested by the multi thread mode of nucmer. As you said, nucmer3 is installed by default. I installed the mummer4 version in my conda env : 

```
# packages in environment at /home/.conda/envs/ragtag:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
curl                      7.83.1               h2283fc2_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
k8                        0.2.5                hd03093a_2    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.83.1               h2283fc2_0    conda-forge
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.47.0               he49606f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_0    conda-forge
libssh2                   1.10.0               ha35d2d1_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libzlib                   1.2.12               h166bdaf_2    conda-forge
minimap2                  2.24                 h7132678_1    bioconda
mummer                    3.23            pl5321h1b792b2_13    bioconda
mummer4                   4.0.0rc1        pl5321h87f3376_3    bioconda
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  2.5.1              pyhd8ed1ab_0    conda-forge
numpy                     1.21.6           py37h976b520_0    conda-forge
openssl                   3.0.5                h166bdaf_1    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pysam                     0.15.3           py37hda2845c_1    bioconda
python                    3.7.12          hf930737_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
ragtag                    2.1.0              pyhb7b1952_0    bioconda
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                63.4.3           py37h89c1867_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.39.2               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.12               h166bdaf_2    conda-forge
```
It seems to work, I don't have any error in my log or in the output directory. This is the command I run : 

`Thu Aug 11 15:30:04 2022 --- INFO: Running: nucmer -t 220 -l 100 -c 500 -p /home/E718/ragtag_hifiasm0.16-nucmer/ragtag.patch.asm /homeE718/ragtag_hifiasm0.16-nucmer/ragtag.patch.ctg.fasta /home/E718/ragtag_hifiasm0.16-nucmer/ragtag.patch.rename.fasta 2> /home/E718/ragtag_hifiasm0.16-nucmer/ragtag.patch.asm.delta.log`

But my `ragtag.patch.asm.delta.log` doesn't get filled gradually ... contrary to my previous conda env (with nucmer 3).

Did you also get something like that @Yutang-ETH ?

Best

**Comment by Yutang-ETH** [comment]
Some updates:

I used external Nucmer 4 (in a different conda environment) with multi-thread option to do alignment first and then copy the delta file to the folder where I am doing RagTag to run RagTag command. The delta file must have this name: ragtag.scaffold.asm.delta
Nucmer 4 command I used is following:
nucmer --maxmatch -t 50 -l 100 -c 500 --delta=ragtag.scaffold.asm.delta reference.fasta asm.fasta
