### ISSUE TITLE
RagTag "patch" not outputting all the results

### ISSUE THREAD

**Issue by DuttaAnik** [malonge/RagTag#95]
Hello,
Thanks a lot for developing this tool. I am trying to use the RagTag `patch` to fill some gaps and improve a genome assembly. Basically, I have two genome assemblies of a wild tomato species, one is a Dovetail assembly and another is Pacbio Hifi assembly. The Dovetail assembly is scaffolded and has longer contiguity whereas the Pacbio is more fragmented. I am trying to use the Pacbio assembly as a query to fill the gaps and improve the scaffolds of the Dovetail target assembly. I am using the following command:
`ragtag.py patch Chile_Dovetail.fasta Chile_HiFi.fa -f 1000 --aligner nucmer --nucmer-params '-l 100 -c 500' -o patched`

The program runs but I obtain only three output files named `ragtag.patch.ctg.agp` `ragtag.patch.ctg.fasta` `ragtag.patch.err`

The .err file is empty. 

Can you please tell me how can I obtain all the necessary files and final `patched.fasta` file for downstream analyses?

I have installed the Ragtag on Ubuntu system.

Thanks. 
Anik

**Comment by malonge** [comment]
Hi there,

The error was probably printed to stderr. Could you share the stderr and then we will see where to go from there.

**Comment by DuttaAnik** [comment]
Hi there,
So, I re-ran the program again with the same command and now I get the following files:
```
ragtag.patch.asm.delta
ragtag.patch.asm.delta.log
ragtag.patch.comps.fasta
ragtag.patch.ctg.agp
ragtag.patch.ctg.fasta
ragtag.patch.ctg.fasta.fai
ragtag.patch.err
ragtag.patch.rename.agp
ragtag.patch.rename.fasta
ragtag.patch.rename.fasta.fai
```
But still, I do not obtain the `ragtag.patch.fasta `which is the final desired fasta file. I also did not receive any error message or anything. Because the .err file is empty.

Any idea what is going on?

**Comment by malonge** [comment]
Hi there,

I will need to look at what is printed to stderr. `ragtag.patch.err` only catches some of the potential errors. But stderr captures most of the logging for ragtag.

**Comment by DuttaAnik** [comment]
Ah ok. Sorry, a stupid question, Can you please tell me how can I print out the stderr?

**Comment by DuttaAnik** [comment]
I will run the code again and let you know.

**Comment by malonge** [comment]
you can do something like this:

```
ragtag.py patch Chile_Dovetail.fasta Chile_HiFi.fa -f 1000 --aligner nucmer --nucmer-params '-l 100 -c 500' -o patched > ragtag.out 2> ragtag.err
```

And then share the contents of `ragtag.err`

**Comment by DuttaAnik** [comment]
Hi there,
The problem was solved. Everything ran perfectly. It was the external server that did not finish the job until the end. 
Many thanks for developing this tool.

Regards
Anik
