### ISSUE TITLE
Hi-C to correct

### ISSUE THREAD

**Issue by Johnsonzcode** [malonge/RagTag#98]
Hello, @malonge 
Thanks for your great work ! 
Can I use Hi-C to correct scaffolds which come from `scaffold` command. If I can, how should I set the perameters ?

**Comment by malonge** [comment]
Hi there,

Unfortunately, RagTag does not offer this function. I know SALSA2 is able to do this.

Thanks

**Comment by Johnsonzcode** [comment]
But I know RagTag offers `correct` function whose `minimap2` `sr` offers correction with NGS reads. Can I use Hi-C as NGS reads?

**Comment by malonge** [comment]
Ah ok I see. I guess I don't explicitly say this, but that feature is only for WGS reads.

**Comment by Johnsonzcode** [comment]
What is the difference between Hi-C reads and WGS reads in the correction step? Before this consult, I am afraid of the chimeric reads, which can not offer true mapping information.

**Comment by malonge** [comment]
RagTag will treat them just like WGS reads and everything will run without errors. But the results, which rely on coverage assumptions, may be inaccurate. I have never tested the correction module with Hi-C data. But it certainly breaks theoretical assumptions about coverage.

**Comment by Johnsonzcode** [comment]
Thank your for your explanation. 
Another question : `ragtag.py scaffold` outputs good continuity scaffolds (369 scaffolds). But `ragtag.py correct` outputs corrected fasta which has too much fragment (2113 scaffolds).
Should I `correct` first then `scaffold` to generate a good continuity but no misassemble assembly ? How I get a  good continuity but no misassemble assembly ?

**Comment by malonge** [comment]
Yes you can correct and then scaffold. Though keep in mind that assemblies don't necessarily need to be corrected. It's up to the user to decide if reference-based correction is appropriate.

**Comment by Johnsonzcode** [comment]
How to correct assembly only with reads ?


 
---Original---
From: "Michael ***@***.***&gt;
Date: 2022/1/17 04:37:08
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [malonge/RagTag] Hi-C to correct (Issue #98)




 
Yes you can correct and then scaffold. Though keep in mind that assemblies don't necessarily need to be corrected. It's up to the user to decide if reference-based correction is appropriate.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Johnsonzcode** [comment]
If I don't correct assembly, I don't know the variation is true or because of the `scaffold` command.
